### ISSUE TITLE
StatsForecast's `compute_forecasts` unintuitive tuples (model, *args)

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/statsforecast#109]
I have been trying to explore the use of an `auto_arima` with a filtered hyperparameter space.

StatsForecasts' calls to the [compute_forecasts](https://github.com/Nixtla/statsforecast/blob/main/statsforecast/core.py#L175) method are fairly unintuitive.  Leveraging the order of unnamed hyperparameters in a tuple to define different models is just weird.

Would it be better for the hyperparameters' control and visibility to define the model with a `partial` function with the fixed hyperparameters?

**Comment by FedericoGarza** [comment]
Solved in v1.0.0.
