### ISSUE TITLE
Uninstalling statsforecast does not completely uninstall module?

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/statsforecast#118]
**Describe the bug**
Uninstalling statsforecast library does not completely uninstall the library. This causes issues in `sktime` checks and the following passes without raising an error after the library has been uninstalled.

```python
 _check_soft_dependencies("statsforecast", severity="error", object=self)
```

**To Reproduce**
```python
!pip install statsforecast

import statsforecast
statsforecast.__version__

!pip uninstall statsforecast

# This passes without any problem, but should have failed since the library has been uninstalled.
# This is essentially what sktime `_check_soft_dependencies` does
import statsforecast

# This fails, but it should have failed above itself
from statsforecast.arima import AutoARIMA as _AutoARIMA
```

**Expected behavior**
After uninstalling, the follownig should raise an exception (`ModuleNotFoundError` or `ImportError`)

**Screenshots**
![image](https://user-images.githubusercontent.com/33585645/168443128-03068d3a-28b2-4c51-8b13-f33f36f85808.png)

**Comment by FedericoGarza** [comment]
Hi @ngupta23! I was able to reproduce the error. It seems to be a problem with how jupyter handles packages. I tried another library and got the same error. Restarting the kernel works.

**Comment by ngupta23** [comment]
@FedericoGarza , yes that is correct. We can close this. Thanks!
