### ISSUE TITLE
[FEAT] Use Dask and Spark clusters

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/statsforecast#119]
**Is your feature request related to a problem? Please describe.**
Scale StatsForecast using Dask and Spark clusters.

**Describe the solution you'd like**
Include [fugue](https://github.com/fugue-project/fugue) as a backend just as we did with Ray.

**Comment by goodwanghan** [comment]
This is great. I will start working on that next week.

**Comment by FedericoGarza** [comment]
Hi @goodwanghan! Do you need some help? :)

**Comment by goodwanghan** [comment]
Hi @FedericoGarza sorry about the delay. I will try to start later this week. We were busy with databricks integrations in the last few weeks.

**Comment by FedericoGarza** [comment]
Relased in v1.0.0.
