### ISSUE TITLE
[FEAT] Add environment variables for `njit`'s `cache=True` and `nogil=True`

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/statsforecast#127]
**Is your feature request related to a problem? Please describe.**
To speed up numba functions, [`cache=True`](https://numba.pydata.org/numba-doc/latest/user/jit.html?highlight=cache#cache) can be used to avoid compilation times each time the function is invoked; and [`nogil=True`](https://numba.pydata.org/numba-doc/latest/user/jit.html?highlight=cache#nogil) can be used to release Python's GIL which can be useful since when doing multiprocessing numba [compiles the function for every process](https://stackoverflow.com/questions/63875749/avoid-recompilation-of-numba-code-when-using-multiprocessing).

**Describe the solution you'd like**
I've been thinking about a solution for a while and I think the best thing to do is to include environment variables for each argument, as suggested [here](https://numba.discourse.group/t/njit-cache-true-best-pratices/1329). 

**Describe alternatives you've considered**
Maybe default both arguments to `True`, but it is too restrictive.

**Comment by FedericoGarza** [comment]
This should also resolve https://github.com/alan-turing-institute/sktime/pull/2527.

**Comment by VivCh14** [comment]
Is there any updates on this ? Seems, currently it is neither directly possible in Numba or in the StatsForecast package. But would be really useful feature.

**Comment by jmoralez** [comment]
This was added in #651
