### ISSUE TITLE
In sample predictions, confidence interval and extract fitted params for Auto ARIMA

### ISSUE THREAD

**Issue by hancelpv** [Nixtla/statsforecast#141]
Hi,

Can you point me to an example where an auto arima model is fitted and the following are generated ?

- In sample predictions
- Confidence or Prediction interval (for both in sample and out sample)
- extracting fitted params (p, d, q etc)

Thanks!

**Comment by jmoralez** [comment]
This can be achieved with the following:
```python
import pandas as pd
from statsforecast.models import AutoARIMA
from statsforecast.utils import AirPassengers

model = AutoARIMA(season_length=12)
model.fit(AirPassengers)
insample_preds = pd.DataFrame(model.predict_in_sample(level=[80, 95]))
forecasts = pd.DataFrame(model.predict(h=2, level=[80, 95]))
parameters = model.model_
```

**Comment by UdaykiranEstario9** [comment]
Can we do this for bulk forecasting
