### ISSUE TITLE
add topic exponential-smoothing

### ISSUE THREAD

**Issue by Beliavsky** [Nixtla/statsforecast#153]
I suggest adding the topic `exponential-smoothing` in the About section.

**Comment by FedericoGarza** [comment]
Thanks for your suggestion, @Beliavsky! Now the topics include `exponential-smoothing` :)

**Comment by mergenthaler** [comment]
@all-contributors please add @FedericoGarza for maintainer

**Comment by mergenthaler** [comment]
@all-contributors please add @FedericoGarza  for maintenance

**Comment by mergenthaler** [comment]
@all-contributors please add @Beliavsky for doc
