### ISSUE TITLE
Passing extra variables for Arima

### ISSUE THREAD

**Issue by alan00775** [Nixtla/statsforecast#160]
This is the present way to use the model:

season_length = 12
horizon = len(Y_test_df)
model = StatsForecast(Y_train_df.set_index('unique_id'), 
                      models=[(auto_arima, season_length)],
                      freq='M', n_jobs=-1)

Few of things I feel missing are:
1. What if I wish to feed in seasonal=False. I can't do that using StatsForecast?
2. What if I wish to restrict max_p, max_q to fixed number say 2. I can't pass that just the way I can do using pmdarima?

**Comment by FedericoGarza** [comment]
Hi @alan00775. As of version 1.0.0.0, you can include these parameters in AutoARIMA (https://nixtla.github.io/statsforecast/)
