### ISSUE TITLE
Naive7/Naive1 Unused External Regressors

### ISSUE THREAD

**Issue by dluuo** [Nixtla/statsforecast#161]
Hello, I saw that when running Naive7/Naive1 the function accepted external regressors (xreg) as an argument, but they do not do anything with the input.

**Comment by FedericoGarza** [comment]
Hi @dluuo! It was a design choice to work correctly with the `StatsForecast` class.  But the `naive` model doesn't use the external regressors.

**Comment by FedericoGarza** [comment]
Hi @dluuo. v1.0.0 address this issue.
