### ISSUE TITLE
Documentation from docstrings with Python standard format and nbdev2.

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/statsforecast#196]
It would be good to have standard python documentation, as many applications operate with docstrings in python standard format.

For example Python's default help function that displays the documentation is not currently working.

Is there a way to create documentation parsing a docstring with nbdev2?
Here for example: https://github.com/Nixtla/statsforecast/blob/main/statsforecast/models.py#L31

**Comment by kdgutier** [comment]
1. It would be also helpful to add the data types to the output functions.
2. Adding a link to the code would be also really useful.

**Comment by FedericoGarza** [comment]
Solved in #209.
