### ISSUE TITLE
Rename ETS to AutoETS

### ISSUE THREAD

**Issue by kdgutier** [Nixtla/statsforecast#218]
The name of the `ETS` class might create confusion across the automatically selected ETS model and simpler models like  `SimpleExponentialSmoothing`, `Holt`, `HoltWinters`.

I suggest to change the name to `AutoETS` to homogenize it with the `AutoARIMA`.
It might be a good idea to make this express change now that `ETS` is a fairly new addition.

**Comment by FedericoGarza** [comment]
Fixed in #318
