### ISSUE TITLE
warnings not imported

### ISSUE THREAD

**Issue by MaxGrtz** [Nixtla/statsforecast#219]
**Describe the bug**
statsforecast/ets.py", line 939, in ets_f 
shows warning: 
```
warnings.warn(
                "I can't handle data with frequency greater than 24. " 
                "Seasonality will be ignored."
            ) 
```
This fails because warnings is not imported.

**Comment by FedericoGarza** [comment]
Hi @MaxGrtz!

Thanks for reporting the issue. It is now fixed in main. The next release will include the fix.
https://github.com/Nixtla/statsforecast/blob/7c9fd0afabbb2b54e49995d823dec6b377046f47/statsforecast/ets.py#L9
