### ISSUE TITLE
Enable levels for forecast_fitted_values

### ISSUE THREAD

**Issue by MaxGrtz** [Nixtla/statsforecast#223]
**Is your feature request related to a problem? Please describe.**
As pointed out in the comment of the code of GroupedArray.forecast, currently ci_levels are provided for the fitted values.
This is useful to have in order to evaluate if the confidence interval covers the true data also for the history.

**Describe the solution you'd like**
Enable ci_levels for forecast_fitted_values

**Comment by kdgutier** [comment]
Hey @MaxGrtz,

For the moment we made the levels available for the normal cross_validation, you may find this a useful alternative while we continue working on this feature.

Here is the [example](https://nixtla.github.io/statsforecast/examples/CrossValidation.html).

**Comment by FedericoGarza** [comment]
Hi @MaxGrtz!

#228 includes the requested functionality. You can find an example (applied to anomaly detection [here](https://nixtla.github.io/statsforecast/examples/UncertaintyIntervals.html)).
