### ISSUE TITLE
[BUG] `forecast` method AutoARIMA

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/statsforecast#226]
**Describe the bug**
`AutoARIMA.forecast` should use the hyperparameters used to instantiate the class.

https://github.com/Nixtla/statsforecast/blob/e8e75e4f43b098a39b0583643a9c7eb3480afaa2/statsforecast/models.py#L275-L283

See, for example, `AutoARIMA.fit`:

https://github.com/Nixtla/statsforecast/blob/e8e75e4f43b098a39b0583643a9c7eb3480afaa2/statsforecast/models.py#L166-L204

**Comment by scatenag** [comment]
:+1:  following...
