### ISSUE TITLE
"Frequency too high" for anything finer than monthly, but I don't have enough data to sample monthly

### ISSUE THREAD

**Issue by astrojuanlu** [Nixtla/statsforecast#227]
**Describe the bug**
I'm trying to follow the ["Getting started" example](https://nixtla.github.io/statsforecast/examples/Getting_Started_with_Auto_Arima_and_ETS.html) with my own data, which happens to be sampled hourly. So I set `season_length = 365 * 24`, but got the following error:

```
...

File /opt/conda/lib/python3.9/site-packages/statsforecast/models.py:245, in ETS.forecast(self, y, h, X, X_future, fitted)
    237 def forecast(
    238         self, 
    239         y: np.ndarray, # time series
   (...)
    243         fitted: bool = False, # return fitted values?
    244     ):
--> 245     mod = ets_f(y, m=self.season_length, model=self.model)
    246     fcst = forecast_ets(mod, h)
    247     keys = ['mean']

File /opt/conda/lib/python3.9/site-packages/statsforecast/ets.py:937, in ets_f(y, m, model, damped, alpha, beta, gamma, phi, additive_only, blambda, biasadj, lower, upper, opt_crit, nmse, bounds, ic, restrict, allow_multiplicative_trend, use_initial_values, maxit)
    935 if m > 24:
    936     if seasontype in ['A', 'M']:
--> 937         raise ValueError('Frequency too high')
    938     elif seasontype == 'Z':
    939         warnings.warn(
    940             "I can't handle data with frequency greater than 24. " 
    941             "Seasonality will be ignored."
    942         )

ValueError: Frequency too high
```

If I resample daily and set `season_length = 365`, I too get a `ValueError: Frequency too high`. Same goes with a weekly resample and `season_length = 52`.

I only have 2 incomplete years of data, so I can't resample monthly: I get various versions of

```
ValueError: order must be 3 non-negative integers, got (0, 0, 0)
```

**To Reproduce**
(I can work on a reproducer if it helps, it will take me some time)

**Expected behavior**
The models work with higher frequencies.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 1.0.0

**Comment by astrojuanlu** [comment]
Sorry, I think I was doing a stupid thing and leaving the `freq` of `StatsForecast` to `M` all this time. Will continue working, sorry for the noise!

**Comment by kdgutier** [comment]
Hi @astrojuanlu,

If you set `season_length = 365 * 24` the implied model would have tens of thousands of parameters.
Have you tried to run the AutoARIMA or AutoETS with `season_length = 24`, on smaller windows of your series?

Additionally both the AutoARIMA and AutoETS require complete inputs.

**Comment by astrojuanlu** [comment]
If now tried `freq="D"` with `season_length=365`, plus `freq="W"` with `season_length=52`, and in both cases it fails. The combination that worked was assuming a seasonality of 1 week instead of 1 year, hence `freq="D"` with `season_length=7`, but the results are very bad.

![image](https://user-images.githubusercontent.com/316517/186996996-4cd3c639-951e-4f4f-8a05-ed424785023e.png)

Bear in mind that I Don't Know What I'm Doing™ so probably I'm asking for an unreasonable thing. But it looks like I should have to look for alternative forecasting methods 😅

**Comment by kdgutier** [comment]
The `freq` argument is meant to identify the temporal granularity of your data.

For example:
-if you have daily data I recommend setting `freq=D` and `seasonal_length=7`.
-if you have monthly data I recommend setting `freq=M` and `seasonal_length=12`.
-if you have weekly data I recommend setting `freq=W` and `seasonal_length=52` or `seasonal_length=4`.

**Comment by kdgutier** [comment]
And you can try other forecasting methods, for example from your plot it looks like a `RandomWalkWithDrift` might give something reasonable. Here is the [models catalog](https://nixtla.github.io/statsforecast/models.html).

**Comment by astrojuanlu** [comment]
>  Did you aggregate your data at the daily level as preprocessing step?

Originally the data is hourly, with gaps. I aggregated it daily, weekly and monthly to see if I could make the models work.

I guess the problem I'm dealing with is that this series has multiple seasonality, and I suppose ARIMA or ETS don't pick that up. I will have a look at the baseline models you suggest and also maybe the newly added MSTL from statsmodels (unreleased, see https://github.com/statsmodels/statsmodels/pull/8160).

**Comment by nelsoncardenas** [comment]
This error was tried to solve in https://github.com/Nixtla/statsforecast/pull/384, I created a new issue showing the new results.

https://github.com/Nixtla/statsforecast/issues/480
