### ISSUE TITLE
Flake8 command not found

### ISSUE THREAD

**Issue by dluuo** [Nixtla/statsforecast#233]
When following [Contributing guide](https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md),  I get the following error when trying to run `flake8 --select=F statsforecast/`:

`zsh: command not found: flake8`

I was able to solve it with `pip install flake8`

**Comment by FedericoGarza** [comment]
Hey @dluuo!

Thanks for reporting this. We have recently added `flake8` to the set of development dependencies:

https://github.com/Nixtla/statsforecast/blob/976d9c742664d6bc206497438715ec4ca3864a57/settings.ini#L21

Does `pip install ".[dev]"` work?
