### ISSUE TITLE
[FEAT] Fitted values for intermittent models 

### ISSUE THREAD

**Issue by AzulGarza** [Nixtla/statsforecast#236]
**Is your feature request related to a problem? Please describe.**
Intermittent models don't have in-sample predictions (or fitted values) implemented. See, for example,

https://github.com/Nixtla/statsforecast/blob/e24068ebe456c8eb6fe68265caf9d60afaa8b60d/statsforecast/models.py#L2253-L2254

**Describe the solution you'd like**
Add in-sample predictions.

**Comment by aeturrell** [comment]
It would be super helpful if there were in-sample predictions available in the **statsforecast** package. Thanks for all the great work.

**Comment by jmoralez** [comment]
This was implemented in #764 and is available since version 1.7.3
