### ISSUE TITLE
Strange behavior of AutoARIMA when forecasting time series with no trend / seasonality

### ISSUE THREAD

**Issue by Garrus990** [Nixtla/statsforecast#242]
**Describe the bug**
Hey guys, I am running a small experiment to compare your implementation of AutoARIMA with the ones that are already there and it works super-cool for seasonal data - I'm impressed. But I found some situations where it works sub-optimally and I would like to draw your attention to that.

**To Reproduce**
I've been using [Synthetic Control Chart Time Series Data Set](https://archive.ics.uci.edu/ml/datasets/synthetic+control+chart+time+series) as my benchmark and there are issues with some time series belonging to the "Normal" group in this dataset (normal group has no trend, seasonality or other remarkable features - it's just lateral trend or noise). 

I found that for some such time series there is a drop in the forecasted values that I do not find explanation for (black series is the truth - I ran a backtesting experiment, AutoARIMA - in green).
![image](https://user-images.githubusercontent.com/31692791/187878124-fc67e921-09fd-4af5-b85d-9af84661ab6c.png)

**Expected behavior**
 Of course I do not expect anything spectacular from such time series, since there is nothing to base a good forecast on, but I'd expect some kind of mean to be the result for such time series.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Package version: 1.0.0

**Comment by FedericoGarza** [comment]
Hey @Garrus990!

Thanks for letting us know about the issue. I have tested the most recent version of StatsForecast, and the forecasts seem stable.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/10517170/193353032-9c40359b-d26b-4bcf-9dbe-d75fd755876a.png">


The following code replicates the pipeline:

```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA

df = pd.read_csv('synthetic_control.data', sep=' ', skipinitialspace=True, header=None)
# select normal series
df = df.loc[0:99]
df.index.name = 'unique_id'
df = df.unstack().reset_index()
df.columns = ['ds', 'unique_id', 'y']
df = df[['unique_id', 'ds', 'y']]
df = df.sort_values(['unique_id', 'ds', 'y'])
df['unique_id'] += 1
df.head()

fcst = StatsForecast(models=[AutoARIMA()], freq=None, n_jobs=-1)
forecasts = fcst.cross_validation(df=df, h=10, n_windows=1)

for id in [3, 46, 58]:
  forecasts.loc[id].set_index('ds').drop('cutoff', axis=1).plot()
  plt.title(f'Normal {id}')
``` 

[Here](https://colab.research.google.com/drive/1gGuRUZwB-iKY-aBD82CdWTEw_AEmPs1P?usp=sharing), you can find the replication using colab. 

Please let us know if you have any questions. :)

**Comment by FedericoGarza** [comment]
Hey @Garrus990, I'm closing this issue, feel free to reopen it if the problem persists :)
