### ISSUE TITLE
ETS class is missing support of 'level' parameter in predict, predict_in_sample and forecast function

### ISSUE THREAD

**Issue by shagn** [Nixtla/statsforecast#248]
**Describe the bug**
Despite the ETS class lists `level` as a parameter which affects the return value in the docstrings of `predict`, `predict_in_sample` and `forecast` function ([models.py](https://github.com/Nixtla/statsforecast/blob/a250036faba7da91129e8227342948aefa11c499/statsforecast/models.py)), all the functions do not accept `level` as a parameter. 

**To Reproduce**
from statsforecast.models import ETS
from statsforecast.utils import AirPassengers as ap
ets = ETS(model='ZMZ',  
          season_length=4)
ets = ets.fit(y=ap)
ets.predict(h=4, level=5)

**Expected behavior**
The function should behave similar to the functions of AutoArima. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16029092/192032033-7d587110-67f3-4761-adfe-5ba94104d746.png)

**Comment by FedericoGarza** [comment]
Hi @shagn! Thanks for letting us know about the issue. Currently, the `ETS` model doesn't include prediction intervals (`level` argument); in the next weeks, we'll release a new version including them. :)

**Comment by kdgutier** [comment]
Meanwhile, an alternative method with available prediction intervals is the `AutoARIMA` class and other simple methods like `Naive`.

Here is the [StatsForecast's model collection](https://nixtla.github.io/statsforecast/models.html#baseline-models)

**Comment by FedericoGarza** [comment]
hey @shagn! The new release of statsforecast (v.1.4.0) includes a fully probabilistic version of the ETS model.
