### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by dalpozz** [Nixtla/statsforecast#25]
I get ValueError: math domain error
cause by 
tmp['bic'] = tmp['aic'] + npar*(math.log(nstar) - 2)
from statsforecast/arima.py", line 1225,

I guess nstar is not > 0

**Comment by jmoralez** [comment]
Thank you for your interest in statsforecast. Are you able to provide some sample data to reproduce the issue?

**Comment by darinkist** [comment]
Facing the same issue. Example:

```
airpassengers_series = pd.DataFrame(
    {
        'ds': np.arange(1, AirPassengers.size + 1),
        'y': AirPassengers
    },
    index=pd.Index(np.arange(len(AirPassengers)),name='unique_id')
)

fcst = StatsForecast(
    airpassengers_series, 
    models=[(auto_arima, 12), (seasonal_naive, 12)], 
    freq='M', 
    n_jobs=1
)
forecasts = fcst.forecast(12)
```

It seems it has sth to do with the index. The index in your "How To" example contains 0s. If I use counting numbers instead (e.g., 0 to 135) then I am getting the math domain error.

**Comment by FedericoGarza** [comment]
Hi @darinkist! The index identifies each time series, so it is correct to use the same number (0) in this case since it is a single time series. If you have more than one time series, then your index must have two different values (one per time series). Using a different index for each row can lead to errors (as you explain) because `StatsForecast` thinks each of them is a time series of size 1. 

We will include more documentation about the input data soon. :)

**Comment by darinkist** [comment]
Hi @FedericoGarza! Thank you for the clarification - makes sense! :)

The reason why I wanted to change the index was bc I am using sklearn's TimeSeriesSplit (for cv), which returns train and test indices that can be used to select/filter the time series data. Then I have to work on a different solution to subset the data :)

**Comment by jmoralez** [comment]
@darinkist the TimeSeriesSplit returns rows indices, so you can use it to split but using `iloc` instead of `loc` like in the following example:
```python
import numpy as np
import pandas as pd
from sklearn.model_selection import TimeSeriesSplit


df = pd.DataFrame({'ds': np.arange(10), 'y': np.random.rand(10)}, index=pd.Index(10 * [0], name='unique_id'))
cv = TimeSeriesSplit(n_splits=3, test_size=2)

for train_idxs, valid_idxs in cv.split(df):
    train_ds = df.iloc[train_idxs]['ds']
    valid_ds = df.iloc[valid_idxs]['ds']
    print(
        f'Train: {train_ds.min()}-{train_ds.max()}. '
        f'Valid: {valid_ds.min()}-{valid_ds.max()}'
    )
```

which yields
```
Train: 0-3. Valid: 4-5
Train: 0-5. Valid: 6-7
Train: 0-7. Valid: 8-9
```

**Comment by darinkist** [comment]
true! ...my bad...  Thank you very much! 👍 Then all issues are solved from my end.
