### ISSUE TITLE
ImportError in AML notebooks

### ISSUE THREAD

**Issue by winnieshen96** [Nixtla/statsforecast#255]
```
----> 3 from statsforecast.models import ADIDA

ImportError: cannot import name 'ADIDA' from 'statsforecast.models' (/anaconda/envs/sktime/lib/python3.9/site-packages/statsforecast/models.py)
```
I want to clarify that the sktime in the file path is just the name I gave to the conda environment. It's not referring to the sktime package.

Environment: a compute on Azure Machine Learning, where conda environments are listed as kernels

**Comment by kdgutier** [comment]
Hi @winnieshen96 

Can you try checking the version of `statsforecast`.
This code runs on Google Colab:
<img width="370" alt="Screen Shot 2022-09-29 at 11 32 29 AM" src="https://user-images.githubusercontent.com/19935241/193075564-23264aed-0198-4b81-a5b7-4f1bceff7fb7.png">

You can upgrade your `statsforecast` version using this line:
`pip install --upgrade statsforecast`

**Comment by winnieshen96** [comment]
Thank you! Somehow it works now. It was probably AML's fault.
