### ISSUE TITLE
exogenous variables on auto_arima

### ISSUE THREAD

**Issue by Yasslight90** [Nixtla/statsforecast#26]
Hi there,

is it possible to add an exogenous variable to auto_arima? I can only see four parameters: y, h, season_length, and approximation.
If yes, would you please show me how ?

Thanks

Yassine

**Comment by FedericoGarza** [comment]
Hi @Yasslight90! We are working on this feature. Stay tuned for the next release! :)

**Comment by FedericoGarza** [comment]
@all-contributors please add @Yasslight90 for idea

**Comment by FedericoGarza** [comment]
Hi @Yasslight90 ! We just released the 0.4.0 version. It includes the exogenous variables feature. 🎉
I'm closing this issue but feel free to open another if you have questions or issues running the model.

**Comment by Yasslight90** [comment]
Perfect! I tested it and it is all good. Thank you for the fast implementation!
