### ISSUE TITLE
[docs] HTML in index notebook messes up online docs

### ISSUE THREAD

**Issue by jmoralez** [Nixtla/statsforecast#28]
This is how the docs render locally for me with the latest changes to the readme. I believe this is due to the embedded html, maybe we can try to achieve that formatting without using html.

![Screenshot from 2022-02-23 21-25-27](https://user-images.githubusercontent.com/8473587/155452279-b8078f4c-d728-4f70-98c9-a71157ad6ec1.png)

**Comment by FedericoGarza** [comment]
🙈 Yes, it's a mess. In `NeuralForecast` we decided to follow the convention that the `README.md` will be changed manually and that `index.ipynb` will have special content for documentation. What do you think? Maybe we can try to achieve the formatting or follow that convention.

**Comment by mergenthaler** [comment]
It def. has some advantages to have different versions of `README.md` and `index.ipynb`. The idea is the former serves as a landing page of the library and the latter as the home page of the documentation. For example I think we should have an [all-contributors](https://github.com/all-contributors/all-contributors) section in the README but not in the index.

**Comment by sugatoray** [comment]
I left a note here. It might be useful for solving this issue.

- https://github.com/Nixtla/statsforecast/pull/24#issuecomment-1052933096

**Comment by mergenthaler** [comment]
@all-contributors please add @jmoralez maintenance

**Comment by FedericoGarza** [comment]
Fixed in v1.0.0 (using nbdev2).
