### ISSUE TITLE
Re-use parameters found by AutoARIMA

### ISSUE THREAD

**Issue by DonLeif** [Nixtla/statsforecast#287]
I want to forward validate several auto AutoARIMA models wrapped in a StatsForecast object (multiple time series).

Is there a way to freeze once found optimal auto arima parameters to re use them (I think it's fair to assume they are relatively stable)?

I could not find such option and think it would be useful for resource-efficient repeated forecasts.

Thanks!

**Comment by cwwang1128** [comment]
I just found a way to do this.

Try this:

`from statsforecast import arima
results2=arima.auto_arima_f(train.values,start_p=6,seasonal=True, start_q=5,max_p=10, max_q=10,max_order=20, period=24,allowdrift=False) #SARIMA model
print(arima.arima_string(results2,padding=False))
`
You can use this code to get the autoarima parameters, and then apply other packages, such as statsmodel, to rebuild your model. 

But it is not efficient.
