### ISSUE TITLE
Tags appear to be missing?

### ISSUE THREAD

**Issue by dhirschfeld** [Nixtla/statsforecast#30]
It makes it easier to understand exactly what code you're running if you can reference the tag in GitHub.

Maybe someone forgot to [`git push --follow-tags`](https://vivaxyblog.github.io/2019/08/02/git-tag-and-push-git-tag.html)?

**Comment by mergenthaler** [comment]
@all-contributors please add @dhirschfeld for question

**Comment by jmoralez** [comment]
@dhirschfeld we've pushed lightweight tags. Do these work for you?

**Comment by dhirschfeld** [comment]
Thanks, that's great! :+1:
