### ISSUE TITLE
[question] Model summary table for ARIMA model

### ISSUE THREAD

**Issue by darinkist** [Nixtla/statsforecast#31]
Hi! I was wondering if you have implemented (or planning to implement) a model summary table for the ARIMA model that contain the coefficients, their p-values, etc.?

Like https://www.statsmodels.org/dev/generated/statsmodels.tsa.arima.model.ARIMAResults.summary.html

Many thanks!

**Comment by kdgutier** [comment]
We have not done it yet, but it can be a really useful addition thanks for the comment.
Potentially `auto.arima` includes already a summary method that can be called, we will take a look.

**Comment by mergenthaler** [comment]
@all-contributors please add @darinkist for ideas

**Comment by FedericoGarza** [comment]
@all-contributors please add @kdgutier for code
