### ISSUE TITLE
[MODELS DOCS] Change ETS to AutoETS 

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/statsforecast#319]
### Description

We are deprecating `ETS` in favor of `AutoETS`. We have to update the documentation accordingly.

**Comment by taniishkaaa** [comment]
can you list all the docs you want to be updated?

**Comment by kvnkho** [comment]
Hi @taniishkaaa,

Are you still interested in working on this? I did a quick search and the only place where I think this needs changing is this page: https://nixtla.github.io/statsforecast/src/core/core.html

The source notebook for that is here: https://github.com/Nixtla/statsforecast/blob/main/nbs/src/core/core.ipynb

And the recently updated contributing instructions can be found here: https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md

Happy to help you with this if you're interested.

**Comment by taniishkaaa** [comment]
hey @kvnkho 
Thanks for getting back to me! I opened a PR for this issue here #561
