### ISSUE TITLE
[question] Division by Zero error 

### ISSUE THREAD

**Issue by tackes** [Nixtla/statsforecast#32]
When running on many groups of time series, some groups are giving me a 'division by zero' error, and the script stops.
Is there a way to pass through this error and complete the forecasts without errors?

**Comment by FedericoGarza** [comment]
Hi @tackes! Would it be possible for you to share with us any time series that gives you the error? To try to replicate and debug it :)

**Comment by tackes** [comment]
The issue is with short time series.  The below will return 2 errors - 
with 
1) random_walk_with_drift will return a **divide by zero** error.
2) arima will return **math domain** error

In the code sample, one removing the 'test' period, it will only have 1 data point to do calculations. 
What would be a nice feature is if there was an option to 'ignore errors' and keep processing.  This particular time series was on the 812th time series group out of 2000, but because it hit an error, the entire script stops running.
Even better is if there was a logging feature to store what and where the error occurred.


`data = {'unique_id': ['A','A','A','A','A'],
        'y':[128050,4200,0,0,0],
        'ds': pd.date_range(end='2021-09-01', periods=5, freq='M')}
series = pd.DataFrame(data,
            columns =['unique_id','y','ds'])

series_test = test_df.groupby('unique_id').tail(horizon).copy()
series = test_df.drop(series_test.index)
series['unique_id'] = series['unique_id'].astype('object')

series = series.set_index('unique_id')
seasonality = 12 #Monthly data
models = [   random_walk_with_drift,   auto_arima]

fcst = StatsForecast(df=series, models=models, freq='M', n_jobs=1)
forecasts = fcst.forecast(horizon)
forecasts.reset_index()`

**Comment by mergenthaler** [comment]
@all-contributors please add @tackes for bug

**Comment by blazespinnaker** [comment]
Get this error as well quite frequently, 

StatsForecast(
            models = [AutoARIMA(season_length = 3)],
            freq = 'M')


 unique_id ds y
40041     2021-10-01  2.607948
40041     2021-09-01  2.613875
40041     2021-08-01  2.646475
40041     2021-07-01  2.667220
40041     2021-06-01  2.673147
40041     2021-05-01  2.705746
40041     2021-04-01  2.693892
40041     2021-03-01  2.735382
40041     2021-02-01  2.690929
40041     2021-01-01  2.578313
