### ISSUE TITLE
[FEAT] make plotly visualizations scalable with plotly-resampler

### ISSUE THREAD

**Issue by jvdd** [Nixtla/statsforecast#342]
### Description

Hi,

First of all, very cool library!! :clap: 

I think it would be interesting to make the plotly.py plots more scalable (i.e., still being responsive at 100M datapoints) by using plotly-resampler. 

The integration can be done by either;
- option A: use plotly-resampler under the hood when the `engine` in `core.GroupedArray.plot` is set to "plotly"
- option B: add "plotly-resampler" as a third option for `engine` in the `core.GroupedArray.plot` method

P.S.: I am one of the two core developers of [plotly-resampler](https://github.com/predict-idlab/plotly-resampler) and open to create a PR to add this functionality. Just want to hear (i) if you are open to this, and (ii) if so, how you would see this integration :slightly_smiling_face: 

### Use case

Having interactivity (i.e., being able to zoom, select, etc.) is crucial when analyzing large and complex data (such as time series). Plotly provides this functionality, but lacks scalability (when dealing with 10-100k+ samples) - hance plotly-resampler performs data aggregation in the back-end (your IPykernel or a seperate dash app) to update your plot dynamically.

**Comment by FedericoGarza** [comment]
Hey @jvdd! Thank you! 

It sounds like a nice enhancement. 

Yes, sure! Please feel free to open a PR with your integration ❤️
