### ISSUE TITLE
[PLOT] Improved customisation for plots 

### ISSUE THREAD

**Issue by robertmartin8** [Nixtla/statsforecast#397]
### Description

It'd be great if the user could do more customisation of the plots. For example, there doesn't seem to be a way to make my plots taller which is a shame (this is a bigger deal than it sounds!)

I think the `sf.plot` function should return the plotting object (e.g. the plotly fig) so that the user can override plot features. Alternatively, perhaps some method of passing kwargs into `sf.plot`.

**Comment by alexdwu13** [comment]
> I think the sf.plot function should return the plotting object
+1

**Comment by FedericoGarza** [comment]
Hey! #465 includes recovering the plotting object for further customization using `fig = sf.plot(df)`. :)
