### ISSUE TITLE
AttributeError: type object 'StatsForecast' has no attribute 'plot'

### ISSUE THREAD

**Issue by kiransview** [Nixtla/statsforecast#402]
AttributeError: type object 'StatsForecast' has no attribute 'plot'

I am trying to plot the series of 8 plots on my local jupyter notebook, it's throwing the above-mentioned error. Can I know what is the issue?
![image](https://user-images.githubusercontent.com/61668526/216913587-e40b63dc-af4d-4668-89b1-a5087d47de5a.png)

**Comment by FedericoGarza** [comment]
Hi @kiransview. Thanks for using statsforecast.

Probably the error arises due to the statsforecast version. Could you try updating the library with `pip install statsforecast -U` or `pip install statsforecast==1.4.0`?

**Comment by kiransview** [comment]
Updating the Library helped in getting this issue resolved.

Thank you
