### ISSUE TITLE
pip and conda version upgrade

### ISSUE THREAD

**Issue by dykim1222** [Nixtla/statsforecast#405]
Hi, 

Thank you for maintaining this package. I was wondering when is the next version update expected for pip and conda.
I could see lots of discrepancies between code on github and code I get from pip install / conda install, and had to edit the code manually.

Is there another way around to get the latest code through pip install or conda install, other than installing directly from github codes?

Thank you.

**Comment by FedericoGarza** [comment]
hey @dykim1222! We just released version 1.5.0 of statsforecast on pip. Let us know if this works. :)

**Comment by dykim1222** [comment]
Thank you @FedericoGarza
