### ISSUE TITLE
[StatsForecast component: Models]: error when executing the documentation and commented imports

### ISSUE THREAD

**Issue by nelsoncardenas** [Nixtla/statsforecast#406]
### Description

In [models](https://github.com/Nixtla/statsforecast/blob/main/nbs/models.ipynb) the documentation has a code on how to use the [ARIMA model](https://nixtla.github.io/statsforecast/models.html#arima), but this code doesn't work.

```python
# ARIMA's usage example

from statsforecast.models import ARIMA
from statsforecast.utils import AirPassengers as ap


arima = ARIMA(order=(1, 0, 0), season_length=12)
arima = arima.fit(y=ap)
y_hat_dict = arima.predict(h=4, level=[80])
y_hat_dict
```

Package version: 1.4.0
Python version: 3.10

Models with this error:
- ARIMA
- AutoRegressive

## Error result

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[50], line 1
----> 1 from statsforecast.models import ARIMA
      2 from statsforecast.utils import AirPassengers as ap
      5 arima = ARIMA(order=(1, 0, 0), season_length=12)

ImportError: cannot import name 'ARIMA' from 'statsforecast.models' (/Users/nelsoncardenas/opt/miniconda3/envs/env_time/lib/python3.10/site-packages/statsforecast/models.py)
```

## Other errors found

While I was analyzing how many models present this same error, I found the documentation has a commented line. 

https://nixtla.github.io/statsforecast/models.html#holt.forward

```python
#from statsforecast.models import Holt
from statsforecast.utils import AirPassengers as ap

model = Holt(season_length=12, error_type='A')
model = model.fit(y=ap)
```

Models with this error:
- https://nixtla.github.io/statsforecast/models.html#holtwinters.forward
- https://nixtla.github.io/statsforecast/models.html#theta.forward
- https://nixtla.github.io/statsforecast/models.html#optimizedtheta.forward
- https://nixtla.github.io/statsforecast/models.html#dynamictheta.forward
- https://nixtla.github.io/statsforecast/models.html#dynamicoptimizedtheta.forward

### Link

https://nixtla.github.io/statsforecast/models.html#arima

- https://nixtla.github.io/statsforecast/models.html#holtwinters.forward
- https://nixtla.github.io/statsforecast/models.html#theta.forward
- https://nixtla.github.io/statsforecast/models.html#optimizedtheta.forward
- https://nixtla.github.io/statsforecast/models.html#dynamictheta.forward
- https://nixtla.github.io/statsforecast/models.html#dynamicoptimizedtheta.forward

**Comment by FedericoGarza** [comment]
hey @nelsoncardenas! Thanks for using statsforecast. The new version (v1.5.0) is now on pip, with this version, you can import the ARIMA model. Let us know if this works.

**Comment by nelsoncardenas** [comment]
![image](https://user-images.githubusercontent.com/18086414/221961558-43f2bdc5-38c1-47aa-a4d8-cff498cd99fa.png)

It is solved! I'll close the issue.
