### ISSUE TITLE
[MSTL] Allow passing parameters through to STL

### ISSUE THREAD

**Issue by robert-robison** [Nixtla/statsforecast#414]
### Description

Hello! Appreciate all the work everyone here has done, have enjoyed using statsforecast.

I have been testing out the `MSTL` method, and would personally benefit from the ability to pass parameters through to the statsmodels `STL` function that it's built on. This functionality exists in both the R `forecast` package and in the new `statsmodels` implementation:

* https://pkg.robjhyndman.com/forecast/reference/mstl.html
* https://www.statsmodels.org/dev/generated/statsmodels.tsa.seasonal.MSTL.html

Should be as simple as just adding an `stl_kwargs` argument.

### Use case

There are several parameters in `STL` that can significantly affect the decomposition it produces. Allowing them as parameters to `MSTL` will increase its flexibility and allow it to better fit the data in many cases

**Comment by FedericoGarza** [comment]
Hey @robert-robison! Thanks for using statsforecast. We've added this new feature in #462. We will publish a new release soon. :)
