### ISSUE TITLE
No Auto-Arima coefficients available (e.g. the p,d,q P,D,Q of the fitted model)

### ISSUE THREAD

**Issue by camfaerber-upside** [Nixtla/statsforecast#417]

**Comment by mokahaiku** [comment]
You are probably looking for `print(model.model_)`

**Comment by C-Zuge** [comment]
Hey!

How could i get these coefficients (p,d,q) found on fit process once `sf.fitted_[0, 0].model_` return a df with decomposition result? 

`
mstl = MSTL(
    season_length=[24,24*7], 
    trend_forecaster=AutoARIMA()
)

sf = StatsForecast(
    models=[mstl],
    freq='H',
)
sf = sf.fit(df)
`

**Comment by jmoralez** [comment]
You can use the ARIMASummary class like the following:

```python
from statsforecast import StatsForecast
from statsforecast.arima import ARIMASummary
from statsforecast.models import AutoARIMA
from statsforecast.utils import AirPassengersDF

sf = StatsForecast(models=[AutoARIMA(season_length=12)], freq='M')
sf.fit(AirPassengersDF)
print(ARIMASummary(sf.fitted_[0, 0].model_))
# ARIMA(1,1,0)(0,1,0)[12]
```
