### ISSUE TITLE
[MSTL] Different results between forecast() and fit() then predict() 

### ISSUE THREAD

**Issue by sammiller06** [Nixtla/statsforecast#443]
### What happened + What you expected to happen

When using a dataset with multiple unique ids, I got different results when calling `forecast()` vs. `fit()` then `predict()`. The former gave the correct results, the latter did not.

### Versions / Dependencies

SF 1.5.3
Python 3.8

### Reproduction script

```
from statsforecast import StatsForecast
from statsforecast.models import MSTL
from neuralforecast.utils import AirPassengersPanel
sf = StatsForecast([MSTL(2)], "D", df=AirPassengersPanel)

# Correct results
print(sf.forecast(3))

## Wrong results
sf.fit()
print(sf.predict(3))
```

### Issue Severity

None

**Comment by FedericoGarza** [comment]
hey @sammiller06! Thank you for letting us know about the issue. We have opened a PR (#446) to solve it. We've also added tests to check that both pipelines return the same outputs. It seems that the problem was only related to MSTL. :)

**Comment by sammiller06** [comment]
Glad to hear, Fede! Feel free to ping me over Slack if you ever want to discuss an issue :)
