### ISSUE TITLE
forbidden component combinations

### ISSUE THREAD

**Issue by sfc-gh-jhu** [Nixtla/statsforecast#445]
https://github.com/Nixtla/statsforecast/blob/57064b9e4e327d4323e0d34c529001da23c060a9/statsforecast/ets.py#L1261

Instead of `(ttype == "M" and stype == "M")`, it should be `(ttype == "M" **or** stype == "M")`? 

According to here:

```
    if restrict:
        if (
            (errortype == "A" and (trendtype == "M" or seasontype == "M"))
            or (errortype == "M" and trendtype == "M" and seasontype == "A")
            or (
                additive_only
                and (errortype == "M" or trendtype == "M" or seasontype == "M")
            )
        ):
            raise ValueError("Forbidden model combination")
```

**Comment by FedericoGarza** [comment]
hey @sfc-gh-jhu! Thanks for letting us know about this issue. #461 fixes it. :)
