### ISSUE TITLE
[AutoCES: column naming] 

### ISSUE THREAD

**Issue by sammiller06** [Nixtla/statsforecast#453]
### What happened + What you expected to happen

When using AutoCES methods like `predict()` and `forecast()`, the results column name is "CES" rather than "AutoCES"

### Versions / Dependencies

1.5.0
Python 3.9

### Reproduction script

Pretty obvious

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey @sammiller06, thanks for using statsforecast. Fixing this would require a breaking change. If you're not comfortable with that name you can provide the alias argument to the constructor, e.g. `AutoCES(alias='AutoCES')`, would that work for you?
