### ISSUE TITLE
[StatsForecast] - forecast_fitted_values fails using Fugue backend 

### ISSUE THREAD

**Issue by jstammers** [Nixtla/statsforecast#454]
### What happened + What you expected to happen

In a previous version of `StatsForecast`, I was able to obtain in-sample errors using `StatsForecast.forecast_fitted_values`.
This seems to be no longer possible when using the Fugue backend

### Versions / Dependencies

StatsForecast: 1.5.0
Fugue: 0.8.2

### Reproduction script

```python
from statsforecast.core import StatsForecast
from statsforecast.models import AutoARIMA
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv')
df["unique_id"] = 1
df = df.rename(columns={"AAPL.High": "y", "Date": "ds"})
model = StatsForecast(models=[AutoARIMA()], freq='D')
forecast = model.forecast(h=1,df=df[["unique_id", "ds", "y"]], fitted=True)
errors = model.forecast_fitted_values()
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by alexeyegorov** [comment]
I think I run into the same problem. It seems that the StatsForecast object does not recognize the option being set.

<img width="1285" alt="Bildschirmfoto 2023-05-11 um 15 28 24" src="https://github.com/Nixtla/statsforecast/assets/5102843/1f2a02e2-229b-4255-b529-692c7d434b6f">

**Comment by agmpt** [comment]
I think I ran into the same problem too.
I intended to replace prophet in a Databricks pipeline that calculates 1M+ forecasts per day. 
In my tests, I had better forecast results with auto_arima than with prophet but ,I need prediction interval and the fit of the model in de historical values and none of them are working with funge backed.
Is there any work around I can do while the bug is not fixed?

<img width="1036" alt="Screenshot_2" src="https://github.com/Nixtla/statsforecast/assets/53531652/293f75e7-b685-45ec-b73a-1bc0f6b99f5c">

**Comment by manuel-munoz-aguirre** [comment]
I ran into this situation too as I need the fitted values to use in `hierarchicalforecast`. A workaround could be to use fugue's `transform` function to call StatsForecast and concatenate fitted (in-sample) values with the forecast. Here's an example with a spark backend:

```python
def sf_fitted(df: pd.DataFrame, freq: str, horizon: int) -> pd.DataFrame:
  df = df.set_index("unique_id")
  df = df.sort_values('ds', ascending=True)

  model = StatsForecast(
    models=[
      AutoARIMA(),
    ], 
    freq=freq,
    n_jobs=1
  )

  # Out-of sample
  Y_hat_df = model.forecast(h=horizon, df=df, fitted=True).reset_index()
  
  # In sample
  Y_fitted_df = model.forecast_fitted_values().reset_index()

  return pd.concat([Y_fitted_df, Y_hat_df], axis=0, ignore_index=True)

out = transform(
  df=Y_train, # pyspark DataFrame
  using=sf_fitted,
  partition={"num": 500, "by": "unique_id"},
  schema="unique_id:str, ds:date, y:float, AutoARIMA:float",
  params={'freq': freq, 'horizon': horizon},
  as_local=False, 
  engine="spark"
)
```
