### ISSUE TITLE
Forecast the M5 Dataset in 5min using Spark clusters link broken!

### ISSUE THREAD

**Issue by ClarisseChia-8451** [Nixtla/statsforecast#466]

**Comment by FedericoGarza** [comment]
hey @ClarisseChia-8451! Thanks for letting us know about the issue. Could you tell us where the broken link is? Thank you! :)

**Comment by kvnkho** [comment]
Working on the Spark documentation now. I think this is the same as this issue: https://github.com/Nixtla/statsforecast/issues/481

Pull request should be out in the next day or two.

**Comment by FedericoGarza** [comment]
Nice @kvnkho! Thank you!❤️
