### ISSUE TITLE
[SeasonalExponentialSmoothing(Optimized)] Model does not consider season of cutoff date correctly 

### ISSUE THREAD

**Issue by thorstenschaefer** [Nixtla/statsforecast#471]
### What happened + What you expected to happen

When creating a forecast for the air passengers example using the SeasES or SeasESOptimized model, the forecast looks plausible, i.e. the seasonality is well captured. Note that airline passengers data contains 144 data points, which is an exact multiple of the seasonality (12 periods)
![image](https://user-images.githubusercontent.com/8972303/233545657-894a4a65-40a5-438d-8fa4-ddfe5e5c056b.png)

Removing the first 6 data points leads to a significant change in the forecast due to the seasonality being "shifted"; expected behavior is that the forecast does not change significantly. 
![image](https://user-images.githubusercontent.com/8972303/233545737-c930767c-6f41-4ef5-910c-fd2889c667c3.png)
Also, if one removes the last 6 data points - i.e., we create a forecast out of a different season - the seasonal structure of the forecast stays the same.

It seems that the model does not check in which season the forecast starts. A code example illustrating the issue follows below; uncomment the second data line to see the effect described.

### Versions / Dependencies

StatsForecast 1.5.0

### Reproduction script

```python
from statsforecast.models import SeasonalExponentialSmoothingOptimized, SeasonalExponentialSmoothing
from statsforecast.utils import AirPassengers as ap

model = SeasonalExponentialSmoothingOptimized(season_length=12)
data = ap[0:] 
#data = ap[6:] 
fc = model.forecast(y=data, h=36, fitted=True)


import matplotlib.pyplot as plt
import numpy as np

fitted = fc['fitted']
plt.plot(fitted) # plotting by columns
plt.plot(([np.NaN] * len(fitted)) + list(fc['mean']))
plt.show()
``` 

### Issue Severity

High: It blocks me from completing my task.

**Comment by FedericoGarza** [comment]
hey @thorstenschaefer! Thank you for letting us know about the issue. It was fixed in #474. We will release a new version soon. In the meantime, installing from the main branch should solve it: `pip install "git+https://github.com/nixtla/statsforecast.git@main"`. 

Here's an example of the forecasts after the fix :)

<img width="885" alt="image" src="https://user-images.githubusercontent.com/10517170/233730505-f72a4d9d-9102-45cd-9966-709b18b075d1.png">
