### ISSUE TITLE
[plot] Add the possibility to select the height of the subplots

### ISSUE THREAD

**Issue by federicodecillia** [Nixtla/statsforecast#478]
### Description

The height of the plots of StatsForecast.plot(engine="plotly") is very small, making it difficult to analyze the various charts.
![2023-05-04 18_54_37-Window](https://user-images.githubusercontent.com/31074088/236272966-7bdbd44f-d79b-45ba-89bf-602160581361.png)

It could be convenient to add the possibility for the user to choose the height of the chart, while currently the height is hard-coded to be 150 in the plotly function of statsforecast/core.py
`fig.update_layout(autosize=True, height=150 * n_rows)`

I tried changing that to 300 for example and the result is much better
![image](https://user-images.githubusercontent.com/31074088/236274694-3357df35-9105-4bcd-bb57-4d56c7bc188b.png)

### Use case

The aim is to let the user to personalize the height of the chart, providing him the ability to customize it to his needs

**Comment by bllguo** [comment]
I suggest at least having the `plot` function return the figure; right now it returns nothing and the plot cannot be customized at all. IMO it would suffice to just be able to write `fig = StatsForecast.plot(...)` and then manipulate `fig` as one would normally

**Comment by jmoralez** [comment]
I believe this was fixed in #465, feel free to reopen if that's not the case.
