### ISSUE TITLE
[arima.py] overflow encountered in subtract

### ISSUE THREAD

**Issue by fehtemam** [Nixtla/statsforecast#479]
### What happened + What you expected to happen

I get the below warning when using AutoARIMA. Should I be concerned about the accuracy of the results or is this something trivial? I think it is related to Numpy:

(/usr/local/lib/python3.10/dist-packages/statsforecast/arima.py:680): RuntimeWarning: overflow encountered in subtract
  x -= np.dot(xreg, par[narma + np.arange(ncxreg)])

### Versions / Dependencies

Python 3.10
statsforecast==1.5.0
numpy==1.23.4

### Reproduction script

@ray.remote
def frcst(id, train_, test_):
    df_tr = train_.loc[train_['unique_id'] == id, :]
    df_ts = test_.loc[test_['unique_id'] == id, :]

    sf = StatsForecast(
        df=df_tr,
        models=[AutoARIMA(season_length=52)],
        freq='W'
    )
    frcst_df = sf.forecast(h=52, level=[95], X_df=df_ts)
    return frcst_df

### Issue Severity

Low: It annoys or frustrates me.

**Comment by holder-fo** [comment]
same problem here. need it fixed asap please.

**Comment by mutecamel** [comment]
Same for me. If this is not a bug, can we safely ignore this warning? @AzulGarza

**Comment by jmoralez** [comment]
Could you provide a minimal reproducible example? References:

* https://matthewrocklin.com/minimal-bug-reports.html
* https://stackoverflow.com/help/minimal-reproducible-example
