### ISSUE TITLE
[Tutorials Spark] 

### ISSUE THREAD

**Issue by nelsoncardenas** [Nixtla/statsforecast#481]
### Description

In this two links are not working:
<img width="854" alt="image" src="https://github.com/Nixtla/statsforecast/assets/18086414/35fa6210-778f-4100-912d-31b4cd2d9057">

My main reason to create the issue was the advice `"If you are particularly interested in this section, please open a GitHub Issue, and we will prioritize it."` 😊

### Link

https://nixtla.github.io/statsforecast/examples/scale/Prophet_spark_m5.ipynb

**Comment by kvnkho** [comment]
I am working on this now, I should have a pull request out in the next day or two.

**Comment by kvnkho** [comment]
Docs has been updated: https://nixtla.github.io/statsforecast/docs/how-to-guides/spark.html

This will be refined but there is also ongoing work around the integration for now that is tracked in other issues so I'll refine the docs once that is done.

Other issues: https://github.com/Nixtla/statsforecast/issues/573 https://github.com/Nixtla/statsforecast/issues/504
