### ISSUE TITLE
CrostonClassic required argument serving no purpose

### ISSUE THREAD

**Issue by nickto** [Nixtla/statsforecast#491]
CrostonClassic has a required argument `level`:
https://github.com/Nixtla/statsforecast/blob/444f01e5014c22ced63e18863314bc75e98f68c5/statsforecast/models.py#L3596

However, 
1. The method is not implemented, so it does not make sense to make it required.
2. None of the other models have `level` as a required argument in `predict_in_sample()` method. 

Hence, it seems like it should be  either
```python
def predict_in_sample(self, level: Optional[Tuple[int]] = None):
```
to be consistent with other methods that use `level` argument.

Or
```python
def predict_in_sample(self):
```
to be consistent with other not implemented methods.

**Comment by kvnkho** [comment]
This should be `def predict_in_sample(self, level: Optional[Tuple[int]] = None):`.

@jaymanalastas, would you like to fix?
