### ISSUE TITLE
Add confidence/prediction intervals

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/statsforecast#5]
As requested [here](https://medium.com/@kevinhankins/i-dont-see-any-forecast-confidence-or-prediction-intervals-in-your-visualization-8e2808f26f74), it would be a great feature including confidence/prediction intervals.

**Comment by justbldwn** [comment]
hello @FedericoGarza , is this feature something that is prioritized on your roadmap? in our org, we just came across your library here and we were really hoping to migrate off of `pmdarima` and onto yours, as the speed of time series forecasting is a huge bottleneck for us.

however after investigating, it looks like [level](https://github.com/Nixtla/statsforecast/blob/22ceff5bac53048fe0802ef301dea8e82e1fb047/statsforecast/arima.py#L1414) isn't used within arima forecasting, whereas we heavily leverage `pmdarima`'s ability to [return the confidence intervals](https://alkaline-ml.com/pmdarima/modules/generated/pmdarima.arima.ARIMA.html?highlight=predict#pmdarima.arima.ARIMA.predict) in our project(s). thanks!
