### ISSUE TITLE
[Ray tutorial] Add a tutorial on how to use statsforecast and ray 

### ISSUE THREAD

**Issue by FedericoGarza** [Nixtla/statsforecast#506]
### Description

Based on https://github.com/Nixtla/statsforecast/issues/504, we want to include a new tutorial using ray instead of spark.

**Comment by FedericoGarza** [comment]
@kvnkho :)

**Comment by kvnkho** [comment]
The previous PR brought this in. This PR will clean it: https://github.com/Nixtla/statsforecast/pull/559

Closing for now.
