### ISSUE TITLE
Mention newly added MLflow support in docs

### ISSUE THREAD

**Issue by benjaminbluhm** [Nixtla/statsforecast#510]
### Description

Thanks for creating the awesome StatsForecast library!

I created a package that adds MLflow support to log StatsForecast models to MLflow and easily deploy them to real-time endpoints using familiar MLflow deployment tools, see the reference in the [latest MLflow docs](https://mlflow.org/docs/latest/community-model-flavors.html#mlflavors)

For a usage example check the [StatsForecast -MLflow](https://mlflavors.readthedocs.io/en/latest/examples.html#statsforecast) tutorial

Proposal is to mention the library as a third-party integration in the StatsForecast docs.

**Comment by FedericoGarza** [comment]
hey @benjaminbluhm! This is really amazing! Thank you very much for working on this integration. ❤️ 

We will include a reference to your library in our docs and make a public announcement soon. :)

**Comment by benjaminbluhm** [comment]
Sounds great @FedericoGarza Look forward to your announcement, much appreciated!

**Comment by kvnkho** [comment]
Docs are live: https://nixtla.github.io/statsforecast/docs/how-to-guides/mlflow.html
