### ISSUE TITLE
Unexpected behavior when "fitting" SeasonalNaive

### ISSUE THREAD

**Issue by christian-hnz** [Nixtla/statsforecast#515]
The fitted values of a `SeasonalNaive` model are all *NaN*s if the time series lengths is less than twice the `season_length` observations.
```
import numpy as np
from statsforecast import models

sn = models.SeasonalNaive(season_length=12)
sn.fit(np.arange(23))
assert np.all(np.isnan(sn.predict_in_sample()['fitted']))
``` 
IMO the fitted values should be 12 *NaN*s followed by 0, 1, 2, ..., 10

The observed behavior is a result of the implementation of `_seasonal_naive` in `util.py`. 

Therein, the `_naive` forecasting function is applied to observations of the same season period except for at most one at the beginning of the time series. More specifically, `y[(i + n % season_length) :: season_length]` is used, which effectively drops all observations of the "leading incomplete cycle" (group the time series in non-overlapping chunks of `season_length` observations starting from the end; the leading incomplete group is disregarded here).

In the above example, this leaves only a single observation for each season period, which is "lost" in `np.roll(y, 1)[1:]` in the `_naive` implementation.

Any interest in pull requests to obtain the above mentioned behavior?

**Comment by jmoralez** [comment]
Thanks for the great report and sorry it took so long to fix this. It was part of the 1.7.1 release.
