### ISSUE TITLE
Error when downloading data

### ISSUE THREAD

**Issue by phihung** [Nixtla/statsforecast#517]
### Description

The ERCOT data used in the following tutorial can not be downloaded from outside the US
https://nixtla.github.io/statsforecast/examples/electricitypeakforecasting.html

```
Access Denied
Error 16
This request was blocked by our security service
```

**Comment by cchallu** [comment]
Hi @phihung! Thanks for detecting this issue.

We will update the tutorial to download the data from s3, as we are doing in our TFT tutorial in Neuralforecast (https://nixtla.github.io/neuralforecast/examples/forecasting_tft.html).
