### ISSUE TITLE
Small error in End to End Walkthrough documentation

### ISSUE THREAD

**Issue by axeltorbenson** [Nixtla/statsforecast#524]
### Description

Error in documentation. I recommend replacing the phrasing circled in red with "The forecasted column must adhere to this naming convention.", or something like that.

![image](https://github.com/Nixtla/statsforecast/assets/72292627/9ff2c2c6-448c-40fe-9b64-6801d86f7190)

### Link

https://nixtla.github.io/statsforecast/examples/getting_started_complete.html

**Comment by kvnkho** [comment]
I am currently making some doc changes and can include this (if you don't want to take a stab at it). If you want to try, I can help with that. My contact info is in my profile.

**Comment by kvnkho** [comment]
This is covered by this pull request: https://github.com/Nixtla/statsforecast/pull/559
