### ISSUE TITLE
[Core] RuntimeWarning Generated by _get_cols 

### ISSUE THREAD

**Issue by kvnkho** [Nixtla/statsforecast#538]
### What happened + What you expected to happen

Running StatsForecast forecast results in a warning:

```
<__array_function__ internals>:200: RuntimeWarning: invalid value encountered in cast
```

Minimum example:

```python
from statsforecast.core import StatsForecast
from statsforecast.models import ( 
    AutoETS,
)
from statsforecast.utils import generate_series

n_series = 4
horizon = 7

series = generate_series(n_series)

models = [
    AutoETS(season_length=7),
    ]

sf = StatsForecast(
    models=models,
    freq='D',
)
sf.forecast(df=series, h=horizon).head()
```

The warnings points to [this line](https://github.com/Nixtla/statsforecast/blob/main/statsforecast/core.py#L81) in core that uses `np.full()`. The error is because we can't use `np.intXX` as the `dtype` when `np.nan` is the fill value since `np.nan` is a float.

We can maybe change the fill value since it gets replaced. Not sure yet on the impact.

### Versions / Dependencies

statsforecast==1.5.0
pandas==1.5.3
numpy==1.24.0

### Reproduction script

To reproduce the warning:
```python
import numpy as np
np.full((2, 2), np.nan, dtype=np.int64)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by FedericoGarza** [comment]
Nice catch @kvnkho! I think it is safe to fill it with `0`.
