### ISSUE TITLE
The statsforecast documentation link is not opening

### ISSUE THREAD

**Issue by snath007** [Nixtla/statsforecast#553]
### Description

When I try to access the doc from https://nixtla.github.io/statsforecast/models.html . Its showing "page not found"
![image](https://github.com/Nixtla/statsforecast/assets/52785444/f0b5223a-b48c-4601-a722-185794e2ef8f)
![Screenshot 2023-06-14 214020](https://github.com/Nixtla/statsforecast/assets/52785444/7b2c6b6a-92c5-469e-90f5-3612d85d73e8)

### Link

https://nixtla.github.io/statsforecast/models.html

**Comment by FedericoGarza** [comment]
hey @snath007! We refactored the documentation. The new link can be found [here](https://nixtla.github.io/statsforecast/src/core/models.html). :)

**Comment by kvnkho** [comment]
I believe this will fix the links in the docs: https://github.com/Nixtla/statsforecast/pull/559/files

**Comment by bgrey001** [comment]
I have the same problem currently, any solution?

**Comment by akmalsoliev** [comment]
> I have the same problem currently, any solution?

this is a new link: https://nixtla.github.io/statsforecast/src/core/models.html

**Comment by sbuse** [comment]
The problem still exist for me. Unfortunately, I can't read any docs (e.g. the quick guide) that are referenced from the main page.

**Comment by akmalsoliev** [comment]
> The problem still exist for me. Unfortunately, I can't read any docs (e.g. the quick guide) that are referenced from the main page.

do you mean this one? https://nixtla.github.io/statsforecast/docs/getting-started/installation.html

**Comment by sbuse** [comment]
Nope, can't reach it. Not even https://nixtla.github.io/statsforecast/

**Comment by akmalsoliev** [comment]
<img width="1348" alt="image" src="https://github.com/Nixtla/statsforecast/assets/24494206/0b0e3cf6-925c-4c53-b8cb-fa1fa2ddf4ef">
that's what I'm seeing, check your ISP provider, might be blocking the website.

**Comment by sbuse** [comment]
Yea i guess it has to do with the company's proxy settings etc. Unfortunately i can't change those.

**Comment by kvnkho** [comment]
@sbuse Can you git clone? You can read the notebooks in the docs folder.

**Comment by kvnkho** [comment]
Doc links are updated. @sbuse , I'm not sure what we can do to help you for now since it seems specific to your network. Though if you find something we can do, just let us know. 

I'll close this issue for now since the original issue is resolved. The docs have just migrated links.

**Comment by sbuse** [comment]
Thanks @kvnkho for the hint with the git clone. This will work for me, and I'm excited to try this repo. It looks amazing, and I was kind of sad to see that I can't access it.
