### ISSUE TITLE
links to data source not working

### ISSUE THREAD

**Issue by alfonsoveneziano** [Nixtla/statsforecast#556]
Hi
could you please update the links on the page https://nixtla.github.io/statsforecast/docs/tutorials/electricityloadforecasting.html?
For instance the link to the 'https://raw.githubusercontent.com/jnagura/Energy-consumption-prediction-analysis/master/PJM_Load_hourly.csv' is not working.

thanks a lot in advance
with regards, alfonso

**Comment by kvnkho** [comment]
Thanks for reporting. Looks like they took down their repo so we'll need another source or place to host the file.
