### ISSUE TITLE
Forecast distributed on Spark doesn't return 'hi' and 'lo' confidence interval

### ISSUE THREAD

**Issue by edgarglzpzz** [Nixtla/statsforecast#573]
I'm running forecasts on a dataset in a distributed way with Spark. In the forecast function I pass the level parameter, however the resulting spark dataframe does not return the 'hi' and 'lo' columns. Even in the [documentation ](https://github.com/Nixtla/statsforecast/blob/main/nbs/docs/how-to-guides/spark.ipynb) about Spark examples, they pass the same parameter and it doesn't return the expected columns.

### Versions / Dependencies

statsforecast==1.5.0

### Reproduction script

backend = FugueBackend(spark, {"fugue.spark.use_pandas_udf":True})

CompiledResult= forecast(
  df = DailySeries,
  models = [MSTL(season_length = [7,28,365], trend_forecaster = AutoETS(model='ZZN')],
  freq = 'D',
  h = 31,
  level = (90,),
  parallel = backend)

### Issue Severity

Low: It annoys or frustrates me.

**Comment by kvnkho** [comment]
This was because the Spark backend uses Fugue, and Fugue had a limitation of not being able to handle arbitrary column names. That limitation was removed recently, so we should be able to make this work now.

I'll take this issue.
