### ISSUE TITLE
[SeasonalNaive]: model with no description

### ISSUE THREAD

**Issue by nelsoncardenas** [Nixtla/statsforecast#574]
### Description

There is no valid description for the SeasonalNaive in the documentation site. **I would like to work on this issue.** For now, I'm just documenting the error

<img width="787" alt="image" src="https://github.com/Nixtla/statsforecast/assets/18086414/c85c8f8b-c8ec-41e7-8e2c-c6d9e40ca5f4">

The code has an error:
<img width="758" alt="image" src="https://github.com/Nixtla/statsforecast/assets/18086414/4755461e-38e5-4873-a8a0-c08933053fde">

### Link

https://nixtla.github.io/statsforecast/src/core/models.html#seasonalnaive

**Comment by kvnkho** [comment]
Thanks for reporting @nelsoncardenas , this PR should fix it soon: https://github.com/Nixtla/statsforecast/pull/575

**Comment by kvnkho** [comment]
Oh I'm sorry. I just had Nixtla open already on VS code and I didn't know the fix so I was just experimenting. I'll close my PR 😁. Please do it and we'll approve yours.

**Comment by nelsoncardenas** [comment]
Thank you @kvnkho. I finish the PR.
