### ISSUE TITLE
Remove parallel and num_cores from AutoARIMA

### ISSUE THREAD

**Issue by mjanson** [Nixtla/statsforecast#576]
### Description

Per the [AutoARIMA pydoc](https://github.com/Nixtla/statsforecast/blob/862cace7a55d9ece478f66337e7ad3d9433ecd01/statsforecast/models.py#L208-L209) was expecting to be able to fit AutoARIMA as follows:

```
df = pd.read_csv('https://datasets-nixtla.s3.amazonaws.com/air-passengers.csv')
sf = StatsForecast(
models = [AutoARIMA(stepwise=False,
                    parallel=True,
                    season_length=12,
                    num_cores=4,
                    trace=False)],
freq = 'M'
)
sf.fit(df)
```

However, in doing so, receiving ```NotImplementedError: parallel=True``` (details in linked gist)

### Link

https://gist.github.com/mjanson/5fa32e7b83fac034eb522e6035e0aa32

**Comment by kvnkho** [comment]
Hi @mjanson , thanks for reporting. I am not 100% what right now, but it does seem like something can be cleaned up. 

I suspect you already know this but just making sure, StatsForecast has parallelism on the data level if you do:

```
sf = StatsForecast(
    df = df, 
    models = models, 
    freq = 'H', 
    n_jobs = -1
)
```

**Comment by kvnkho** [comment]
After further discussion with @FedericoGarza , we should not have parallelism at the model level. It should only be at the data level handled by the StatsForecast class. As such, we should remove the `parallel` and `num_cores` kwargs from AutoARIMA.

**Comment by ngupta23** [comment]
Thanks for reporting. This should be fixed by this: https://github.com/pycaret/pycaret/pull/3731
