### ISSUE TITLE
[How-to guides| AutoARIMA Comparison (Prophet and pmdarima)] Notebook not found

### ISSUE THREAD

**Issue by nelsoncardenas** [Nixtla/statsforecast#589]
### Description

AutoARIMA Comparison (Prophet and pmdarima) contains a Colab link that is not working.

<img width="665" alt="image" src="https://github.com/Nixtla/statsforecast/assets/18086414/3099468b-e81d-468f-9077-9ed2c7a51b06">

### Link

* https://nixtla.github.io/statsforecast/docs/how-to-guides/autoarima_vs_prophet.html#example
* https://colab.research.google.com/github/Nixtla/statsforecast/blob/main/nbs/examples/AutoArima_vs_Prophet.ipynb

**Comment by jmoralez** [comment]
This has been fixed as well.
