### ISSUE TITLE
What are the hard dependencies of statsforecast?

### ISSUE THREAD

**Issue by tim-manns** [Nixtla/statsforecast#596]
Hello,

I'm keen to use statsforecast in AWS Lambda but the package size of 700MB is unwieldy.  Fyi - limits of 250mb for python packages are common.  I need to delete some packages and run statsforecast without many of the packages that are installed with a standard "pip install statsforecast"

I cannot find mention of the hard dependencies.   Which packages are truly needed?

Thanks 
Tim

**Comment by kvnkho** [comment]
Yeah...this is related: https://github.com/Nixtla/statsforecast/issues/509

Unfortunately, I think plotly is a bit hardcoded now. It would take a bit of work to move the imports around, but definitely worth doing.

**Comment by kvnkho** [comment]
I took a stab at removing plotly dependency, but the matplotlib and plotly code is not quite 1:1 yet. This will need a bit more time.
