### ISSUE TITLE
[Core] Defining Prediction Interval in StatsForecast Class Doesn't Propagate to Models

### ISSUE THREAD

**Issue by kvnkho** [Nixtla/statsforecast#598]
### What happened + What you expected to happen

There are two places to define `ConformalIntervals`. One is that the model level, and the second one is that the `StatsForecast` level. Defining it at the `StatsForecast` level doesn't work for now. Presumably, we want to apply it to all models that have no intervals defined.

### Versions / Dependencies

Master branch (will be present in 1.6)

### Reproduction script

```python
from statsforecast.models import SimpleExponentialSmoothing, ADIDA
from statsforecast.utils import ConformalIntervals
from statsforecast import StatsForecast

models = [
    SimpleExponentialSmoothing(alpha=0.1),
    ADIDA()
]

res = StatsForecast(
    df=train, 
    models=models, 
    freq='H').forecast(h=24, prediction_intervals=ConformalIntervals(h=24, n_windows=2)) 

res.head().reset_index()
```

### Issue Severity

Low - there is a simply workaround

**Comment by jmoralez** [comment]
I think this works if you also set the level, e.g.
```python
res = StatsForecast(
    df=train, 
    models=models, 
    freq='H').forecast(h=24, prediction_intervals=ConformalIntervals(h=24, n_windows=2), level=[80, 95]) 
```
So the bug here is not raising an error when level is not passed?

**Comment by kvnkho** [comment]
Ah if that is the case, then I guess so. I didn't spend that much time tracking it, but yeah sounds like we should just raise an error.
