### ISSUE TITLE
ImportError: cannot import name 'seasonal_naive' from 'statsforecast.models'

### ISSUE THREAD

**Issue by merajhasan88** [Nixtla/statsforecast#606]
On a jupyter notebook with Windows, and Python `3.11.4`, while trying to import `seasonal_naive` I get an error:
```
ImportError: cannot import name 'seasonal_naive' from 'statsforecast.models'
```

I ran this code from [this](https://pypi.org/project/statsforecast/0.5.6/) pypi link:
```
import numpy as np
import pandas as pd
from IPython.display import display, Markdown

import matplotlib.pyplot as plt
from statsforecast import StatsForecast
from statsforecast.models import seasonal_naive, auto_arima
from statsforecast.utils import AirPassengers
```
I have `statsforecast-1.5.0 statsmodels-0.14.0`.
What am I doing wrong?

**Comment by mapabu** [comment]
I think the name is SeasonalNaive. 

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
from statsforecast.models import AutoETS
from statsforecast.models import AutoCES
from statsforecast.models import AutoTheta
from statsforecast.models import SeasonalNaive

**Comment by kvnkho** [comment]
@mapabu is right here. Let me know if you have any other issues, otherwise I'll close the issue for now. Feel free to just re-open though.
