### ISSUE TITLE
[FugueBackEnd] Adding exogenous variables generates error in cross_validation

### ISSUE THREAD

**Issue by edgarglzpzz** [Nixtla/statsforecast#608]
### What happened + What you expected to happen

Hello, I have a problem with adding exogenous variables using a spark dataframe.

I recieved the following error: 
```python
PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fugue_spark/execution_engine.py", line 215, in _udf_pandas
    output_df = map_func(cursor, input_df)
  File "/usr/local/lib/python3.10/dist-packages/fugue/extensions/_builtins/processors.py", line 333, in run
    return self.transformer.transform(df)
  File "/usr/local/lib/python3.10/dist-packages/fugue/extensions/transformer/convert.py", line 346, in transform
    return self._wrapper.run(
  File "/usr/local/lib/python3.10/dist-packages/fugue/dataframe/function_wrapper.py", line 100, in run
    return self._rt.to_output_df(rt, output_schema, ctx=ctx)
  File "/usr/local/lib/python3.10/dist-packages/fugue/dataframe/function_wrapper.py", line 352, in to_output_df
    output = output[_schema.names]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['price'] not in index"
```
In this case, 'price' is the name of the exogenous variable in the spark dataframe.

### Versions / Dependencies

statsforecast == 1.5.0

### Reproduction script
```python
from pyspark.sql import SparkSession
from statsforecast.core import StatsForecast
from statsforecast.models import (MSTL)
from statsforecast.utils import generate_series

spark = SparkSession.builder.getOrCreate()


n_series = 4
horizon = 7

# Make unique_id a column
series = generate_series(n_series)
series = series.reset_index()
series['unique_id'] = series['unique_id'].astype(str)

sf = StatsForecast(
    models=[MSTL(season_length=[7,14])],
    freq='D',
)

# Convert to Spark
sdf = spark.createDataFrame(series).\
withColumn('price', lit(10)) ## Example using an exogenous variable ##

# Returns a Spark DataFrame
sf.cross_validation(df=sdf, h=horizon, step_size = 24,
    n_windows = 2, level=[90]).show()
```
### Issue Severity

High: It blocks me from completing my task.

**Comment by kvnkho** [comment]
I'll take a look at this

**Comment by edgarglzpzz** [comment]
Thank you @kvnkho! :)

**Comment by jmoralez** [comment]
I think the problem is here https://github.com/Nixtla/statsforecast/blob/843ae11eda034a71ef0af9e619dec20c7d587675/statsforecast/distributed/fugue.py#L181 the output schema is considering the exogenous feature (`price`), but the cross_validation method doesn't return it. I'll try to work on a fix.

**Comment by joeackers** [comment]
Hi @jmoralez  I seem to getting the same issue as the above. 

This is my script:

models = SparkXGBForecast(random_state=0)

fcst = DistributedMLForecast(
    models=models,
    freq='W',
    lags=lags,
    lag_transforms=lag_transforms,
    date_features=dates,
    target_transforms=[Differences([1])],
)

cv_results = fcst.cross_validation(
    df=model_df,
    h=4,
    n_windows=2,
    id_col = 'unique_id',
    target_col='SalesQty',
    time_col='WeekStartDate',
    static_features=['Fascia_index', 'LocationName_index']
)

Which runs fine, but when I then and try calling cv_results ie .show() I get this error
keyError: "['SellingPrice', 'WeeksinBusiness', 'Label_index', 'ReportingSubCategory_index'] not in index"

The features in the error are all those that are not included in my static features. Did a fix ever go in for this?

**Comment by jmoralez** [comment]
@joeackers this is the statsforecast repo. Please open an issue in the mlforecast repo.
