### ISSUE TITLE
AutoARIMA crashs if unexpected column in dataframe

### ISSUE THREAD

**Issue by StefanWiegandSSW** [Nixtla/statsforecast#618]
### What happened + What you expected to happen

If the dataframe used to train AutoARIMA contains an additional column not just the expected unique_id | ds | y it crashes during sf.predict()

I would expect it to ignore the additional col.

### Versions / Dependencies

Colab

### Reproduction script
```python
import pandas as pd
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
from statsforecast.utils import AirPassengersDF

df_all = AirPassengersDF
# Extract the month from the 'ds' column and add it as a new column
df_all['ds'] = pd.to_datetime(df_all['ds'])
df_all['month'] = df_all['ds'].dt.month # comment this line to make code run

sf = StatsForecast(
    models = [AutoARIMA(season_length = 12)],
    freq = 'M'
)
sf.fit(df_all)
sf.predict(h=12)
```

### Issue Severity

Low: It annoys or frustrates me.

**Comment by jmoralez** [comment]
Hey @StefanWiegandSSW, thanks for using statsforecast. The issue here is that the month is being used as an exogenous feature by the ARIMA model (not being ignored), so it expects the future values to be provided when predicting. You can find more details in [this guide](https://nixtla.github.io/statsforecast/docs/how-to-guides/exogenous.html).

Here's a modified version of your script:
```python
import pandas as pd
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
from statsforecast.utils import AirPassengersDF

df_all = AirPassengersDF
# Extract the month from the 'ds' column and add it as a new column
df_all['ds'] = pd.to_datetime(df_all['ds'])
df_all['month'] = df_all['ds'].dt.month
valid = df_all.tail(12)
train = df_all.drop(valid.index)

sf = StatsForecast(
    models = [AutoARIMA(season_length = 12)],
    freq = 'M'
)
sf.fit(train)
sf.predict(h=12, X_df=valid.drop(columns='y'))
```

Please let us know if you have further doubts.

**Comment by StefanWiegandSSW** [comment]
Great, thanks for taking the time to explain the issue. I didn't know ARIMA could handle exogenous variables.
It would have been great if the error message hinted at the missing X_df.

**Comment by petertadrous** [comment]
When running the original example, I get `Exception: No regressors provided` raised from the base `Exception` class., raised here:
https://github.com/Nixtla/statsforecast/blob/fea15812501f65b93ea7e86dd12a064167255825/statsforecast/arima.py#L1581

and also found here:

https://github.com/Nixtla/statsforecast/blob/fea15812501f65b93ea7e86dd12a064167255825/statsforecast/arima.py#L1356

Perhaps a more descriptive exception, such as `TypeError` or a `MissingExogenous` inheriting from `TypeError` would be useful?

```
class MissingExogenous(TypeError):
    def __init__(self, message="Expected exogenous regressors, none provided"):
        super().__init__(self.message)
```

**Comment by jmoralez** [comment]
Thanks @petertadrous, we're going to add some general validations with more helpful error messages before it gets to that point.
