### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/statsforecast#62]
Currently the library has a restrictive copyleft license. This prevents it from being added to other libraries. See [discussion here](https://www.linkedin.com/feed/update/urn:li:activity:6902012650709204992?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6902012650709204992%2C6902192208720617472%29). Would it be possible to change the license to a more permissive one like MIT or BSD?

[GPL Copyleft](https://en.wikipedia.org/wiki/GNU_General_Public_License#:~:text=The%20GPL%20series%20are%20all,same%20or%20equivalent%20license%20terms)

BSD or MIT might be better alternatives: https://en.wikipedia.org/wiki/BSD_licenses

![image](https://user-images.githubusercontent.com/33585645/157331210-88311192-21e2-4a9a-80cd-7503e7c86306.png)

**Comment by FedericoGarza** [comment]
Hi @ngupta23! We changed the LICENSE to MIT. The next pypi and conda release will include the new license. :)

**Comment by ngupta23** [comment]
Thank you. That was quick!

**Comment by aiwalter** [comment]
great guys, that is good news :)
