### ISSUE TITLE
Can't Use GARCH ARCH model

### ISSUE THREAD

**Issue by jugeshPrajapati** [Nixtla/statsforecast#637]
ImportError: cannot import name 'GARCH' from 'statsforecast.models'

I don't see any ARCH family model in models.py

# %% auto 0
__all__ = ['AutoARIMA', 'AutoETS', 'ETS', 'AutoCES', 'AutoTheta', 'SimpleExponentialSmoothing',
           'SimpleExponentialSmoothingOptimized', 'SeasonalExponentialSmoothing',
           'SeasonalExponentialSmoothingOptimized', 'Holt', 'HoltWinters', 'HistoricAverage', 'Naive',
           'RandomWalkWithDrift', 'SeasonalNaive', 'WindowAverage', 'SeasonalWindowAverage', 'ADIDA', 'CrostonClassic',
           'CrostonOptimized', 'CrostonSBA', 'IMAPA', 'TSB', 'MSTL', 'Theta', 'OptimizedTheta', 'DynamicTheta',
           'DynamicOptimizedTheta']

**Comment by jmoralez** [comment]
Hey @jugeshPrajapati, those models have been in statsforecast since 1.5.0. Which version are you using?

**Comment by jugeshPrajapati** [comment]
It was the latest version, but it did not work so I installed 1.0.0, it still did not work so I downloaded statsforcast folder from GitHub which includes the GARCH model and I replaced the statsforcast folder in the package from the downloaded folder.
So it started working but I got another error after replacing the folder.

```
from sktime.datasets import load_airline
from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
y = load_airline()
forecaster = StatsForecastAutoARIMA(  
    sp=12, d=0, max_p=2, max_q=2
)
forecaster.fit(y)  
y_pred = forecaster.predict(fh=[1,2,3]) 
TypeError: __init__() got an unexpected keyword argument 'parallel'
```
What should I do, if I don't replace the file I will get the  (GARCH) model error , otherwise this error.

```
from sktime.forecasting.arch import StatsForecastARCH,StatsForecastGARCH
arch =StatsForecastARCH(p=0)
arch.fit(y=df)
ImportError: cannot import name 'ARCH' from 'statsforecast.models' 
```

**Comment by jmoralez** [comment]
Are you using other functionalities from sktime? You can avoid both errors by using statsforecast directly.
