### ISSUE TITLE
Exogenous regressor with AutoEts not taken into account 

### ISSUE THREAD

**Issue by GGA-PERSO** [Nixtla/statsforecast#652]
### What happened + What you expected to happen

While using AutoETS model, MAE with exogenous regressors = MAE without exogenous regressors   
 
Normally it should not be equal 

To reproduce you can use  the colab notebook => unstead of Auto_Arima change the model by Auto_ETS

### Versions / Dependencies

statsforecast 1.6.0

### Reproduction script

https://colab.research.google.com/github/Nixtla/statsforecast/blob/main/nbs/docs/how-to-guides/Exogenous.ipynb

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @GGA-PERSO, thanks for using statsforecast. The AutoETS model can't use exogenous regressors, the argument is there for compatibility, sorry for the confusion.

**Comment by GGA-PERSO** [comment]
Ok it makes sense. I was curious to know how it was possible but now crystal clear.
