### ISSUE TITLE
input dataframe expects hard-requirement of columns as ds, unique_id

### ISSUE THREAD

**Issue by ashigro** [Nixtla/statsforecast#655]
Should this hard requirement exist? and if it should exist, then we must mention in help of functions otherwise it require hit and trial method for fixing errors.

**Comment by ashigro** [comment]
I was struggling with statsforecast libraries since morning. I believe we should precisely mention the input dataframe requirements for StatsForecast library.
One should understand by looking at help
?StatsForecast

**Comment by jmoralez** [comment]
Hey @ashigro, thanks for using statsforecast. I see the docstring for StatsForecast and the methods that take a dataframe all have this information:
https://github.com/Nixtla/statsforecast/blob/cbcfe2560d627f12a68507958bb1f847d06f2cae/statsforecast/core.py#L1582-L1583
https://github.com/Nixtla/statsforecast/blob/cbcfe2560d627f12a68507958bb1f847d06f2cae/statsforecast/core.py#L857-L858
https://github.com/Nixtla/statsforecast/blob/cbcfe2560d627f12a68507958bb1f847d06f2cae/statsforecast/core.py#L998-L999
https://github.com/Nixtla/statsforecast/blob/cbcfe2560d627f12a68507958bb1f847d06f2cae/statsforecast/core.py#L1056-L1057

Can you point to us where this is missing?

**Comment by akmalsoliev** [comment]
@ashigro @jmoralez A bit confusing, I am pretty sure if the DataFrame doesn't have required column then a hint error will be raised. https://github.com/Nixtla/statsforecast/blob/4829b99e4d62ac11b37063e94bdae7351bbce215/statsforecast/core.py#L632
