### ISSUE TITLE
StatsForecast.forecast_fitted_values() - issue with returning fitted values for Croston Models

### ISSUE THREAD

**Issue by mwhlgmth** [Nixtla/statsforecast#664]
### What happened + What you expected to happen

I am using a number of StatsForecast models for a task. When returning the in-sample predictions I encounter an error when I include any of the Croston Models. The issue has been described also by other users of the library, e.g. here: 

https://stackoverflow.com/questions/77214782/how-to-get-fitted-valuesinsample-forecast-for-model-where-fitted-true-is-not-i

This is the error message I get: 

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/statsforecast/core.py", line 193, in forecast
    res_i = model.forecast(
  File "/opt/conda/lib/python3.10/site-packages/statsforecast/models.py", line 4074, in forecast
    res = _croston_classic(y=y, h=h, fitted=fitted)
  File "/opt/conda/lib/python3.10/site-packages/statsforecast/models.py", line 3915, in _croston_classic
    raise NotImplementedError("return fitted")
NotImplementedError: return fitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.10/site-packages/statsforecast/core.py", line 198, in forecast
    res_i = fallback_model.forecast(
AttributeError: 'list' object has no attribute 'forecast'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[33], line 8
      1 fcst = StatsForecast(
      2     df=Y_train_df, 
      3     models=[CrostonClassic()], #AutoARIMA(season_length=seasonality), CrostonClassic()
   (...)
      6     n_jobs=-1
      7 )
----> 8 Y_hat_df = fcst.forecast(h=horizon, fitted=True, level=LEVEL)
      9 Y_fitted_df = fcst.forecast_fitted_values()

File /opt/conda/lib/python3.10/site-packages/statsforecast/core.py:1899, in StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df, prediction_intervals)
   1895     raise ValueError(
   1896         "You must specify `level` when using `prediction_intervals`"
   1897     )
   1898 if self._is_native(df=df):
-> 1899     return super().forecast(
   1900         h=h,
   1901         df=df,
   1902         X_df=X_df,
   1903         level=level,
   1904         fitted=fitted,
   1905         sort_df=sort_df,
   1906         prediction_intervals=prediction_intervals,
   1907     )
   1908 assert df is not None
   1909 engine = make_execution_engine(infer_by=[df])

File /opt/conda/lib/python3.10/site-packages/statsforecast/core.py:1097, in _StatsForecast.forecast(self, h, df, X_df, level, fitted, sort_df, prediction_intervals)
   1087     res_fcsts = self.ga.forecast(
   1088         models=self.models,
   1089         h=h,
   (...)
   1094         verbose=self.verbose,
   1095     )
   1096 else:
-> 1097     res_fcsts = self._forecast_parallel(h=h, fitted=fitted, X=X, level=level)
   1098 if fitted:
   1099     self.fcst_fitted_values_ = res_fcsts["fitted"]

File /opt/conda/lib/python3.10/site-packages/statsforecast/core.py:1395, in _StatsForecast._forecast_parallel(self, h, fitted, X, level)
   1383     future = executor.apply_async(
   1384         ga.forecast,
   1385         (
   (...)
   1392         ),
   1393     )
   1394     futures.append(future)
-> 1395 out = [f.get() for f in futures]
   1396 fcsts = [d["forecasts"] for d in out]
   1397 fcsts = np.vstack(fcsts)

File /opt/conda/lib/python3.10/site-packages/statsforecast/core.py:1395, in <listcomp>(.0)
   1383     future = executor.apply_async(
   1384         ga.forecast,
   1385         (
   (...)
   1392         ),
   1393     )
   1394     futures.append(future)
-> 1395 out = [f.get() for f in futures]
   1396 fcsts = [d["forecasts"] for d in out]
   1397 fcsts = np.vstack(fcsts)

File /opt/conda/lib/python3.10/multiprocessing/pool.py:774, in ApplyResult.get(self, timeout)
    772     return self._value
    773 else:
--> 774     raise self._value

AttributeError: 'list' object has no attribute 'forecast'

### Versions / Dependencies

Python 3.10.12
StatsForecast version: 1.6.0

### Reproduction script

import numpy as np
import pandas as pd
from statsforecast.core import StatsForecast
from statsforecast.models import AutoARIMA, Naive, CrostonClassic
from datasetsforecast.hierarchical import HierarchicalData, HierarchicalInfo

# ['Labour', 'Traffic', 'TourismSmall', 'TourismLarge', 'Wiki2']
dataset = 'TourismSmall' # 'TourismLarge'
verbose = True
intervals_method = 'bootstrap'
LEVEL = np.arange(0, 100, 2)

dataset_info = HierarchicalInfo[dataset]
Y_df, S_df, tags = HierarchicalData.load(directory=f'./data/{dataset}', group=dataset)
Y_df['ds'] = pd.to_datetime(Y_df['ds'])

# Train/Test Splits
horizon = dataset_info.horizon
seasonality = dataset_info.seasonality
Y_test_df = Y_df.groupby('unique_id').tail(horizon)
Y_train_df = Y_df.drop(Y_test_df.index)
Y_test_df = Y_test_df.set_index('unique_id')
Y_train_df = Y_train_df.set_index('unique_id')

# Create forecast and fitted DataFrame
fcst = StatsForecast(
    df=Y_train_df, 
    models=[CrostonClassic()], #AutoARIMA(season_length=seasonality), 
    fallback_model=[Naive()],
    freq='M', 
    n_jobs=-1
)
Y_hat_df = fcst.forecast(h=horizon, fitted=True, level=LEVEL)
Y_fitted_df = fcst.forecast_fitted_values()

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by nanw16** [comment]
I wonder if you would consider adding the implementation of fitted insample prediction for the Croston family. Thanks!

**Comment by mjsandoval04** [comment]
is there any update about this? I'm also getting a "NotImplementedError: return fitted" when implementing the fitted in-sample prediction for the Croston Classic family. We need the fitted in-sample prediction for these models 🙏🙏🙏 thanks !!!
