### ISSUE TITLE
[Core]  Getting Exception: Please run `forecast` mehtod using `fitted=True`

### ISSUE THREAD

**Issue by iamyihwa** [Nixtla/statsforecast#673]
### What happened + What you expected to happen

When I am using pyspark dataframe to forecast, doesn't give me option to get fitted_value. 

### Versions / Dependencies

1.6.0
Linux 

### Reproduction script

`
import random
import pandas as pd

start_date = pd.to_datetime('2020-01-01')
end_date = start_date + pd.DateOffset(weeks=28)
date_range = pd.date_range(start=start_date, end=end_date, freq='W')
vals = [random.randint(1, 100) for _ in range(28)]

test_df = pd.DataFrame({'unique_id': ['country']*28 , 'ds': date_range, 'y': vals})

#Y_df_train.items = Y_df_train.iteritems
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA, SeasonalNaive

sf = StatsForecast(
    models = [ AutoARIMA(season_length = 12 )],# SeasonalNaive(season_length = 12)], #
    freq = 'W',   
    fallback_model = SeasonalNaive(season_length = 12), 
    df = test_df # Y_df_train.set_index('unique_id')
)

res = sf.forecast(h = 13, fitted=True ) # .cache()
insample_res = sf.forecast_fitted_values()

test_df.iteritems = test_df.items
test_sf = spark.createDataFrame(test_df)

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA, SeasonalNaive

sf = StatsForecast(
    models = [AutoARIMA(season_length = 12 )],# SeasonalNaive(season_length = 12)], #
    freq = 'W',   
    fallback_model = SeasonalNaive(season_length = 12), 
  
)

res = sf.forecast(df = test_sf,h = 13, fitted=True ) # .cache()
insample_res = sf.forecast_fitted_values()

`

Lower part, which uses spark dataframe gives error, where upper part that uses pandas dataframe doesn't . 

![image](https://github.com/Nixtla/statsforecast/assets/12494156/c73aeb1b-fa4b-4b1c-8c20-faee897c1f56)

### Issue Severity

None

**Comment by jmoralez** [comment]
Closing in favor of #454
