### ISSUE TITLE
Fiscal quarters are not handled properly. test_size in cross validation function does not work.

### ISSUE THREAD

**Issue by robertasgabrys** [Nixtla/statsforecast#680]
Hello, 

I am using the Holt-Winters model to predict Nike's quarterly revenue. For some companies(Nike, Walmart. Microsoft, etc), fiscal quarters do not align with calendar quarters. However, when I forecast into the future, the output aligns with calendar quarters. This discrepancy is also evident in the results from the cross_validation method. I suspect that the seasonal_length parameter might be defaulting to calendar-based seasons.

![Screenshot 2023-10-29 225205](https://github.com/Nixtla/statsforecast/assets/31359004/6c1e8731-989e-4e96-ba73-4ae808845dc9)

Additionally, I encounter an error when I attempt to specify test_size in the cross_validation() method, rather than using n_windows(). It also changed the fiscal quarters to calendar quarters. 
![Screenshot 2023-10-29 230408](https://github.com/Nixtla/statsforecast/assets/31359004/84b778cd-b811-4aaa-879d-564217522799)

Thank you!

**Comment by jmoralez** [comment]
Hey. This isn't related to the `season_length`, but with the `freq` argument. That argument is used to offset the dates to build the predictions dataframe. In this case I believe you can use `freq=3M'`, which will instead add three months.
