### ISSUE TITLE
Conformal Prediction returns error for dataframes with series of unequal length

### ISSUE THREAD

**Issue by baniasbaabe** [Nixtla/statsforecast#686]
### What happened + What you expected to happen

I would expect that there wouldn't be any issues since the model will be trained separately on every unique_id, but if you have a dataframe with timeseries of unequal length for every id, you will get an error. 

```
ValueError: operands could not be broadcast together with shapes (7,) (2,) 
```

### Versions / Dependencies

1.5.0

### Reproduction script

```python
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Define the number of unique IDs and the maximum length of the time series in hours
num_ids = 5
max_length = 24  # For example, maximum of 24 hours

# Create an empty DataFrame
df = pd.DataFrame(columns=['unique_id', 'ds', 'y'])

# Seed the random number generator for reproducibility
np.random.seed(0)

# Generate time series data of unequal length for each unique ID
for i in range(num_ids):
    # Generate a random start date and time for each unique_id
    start_datetime = datetime(2023, 1, 1) - timedelta(hours=np.random.randint(1, 100))
    
    # Generate a random length for the time series (less than max_length)
    length = np.random.randint(1, max_length)
    
    # Create a date range for the time series with hourly frequency
    datetimes = [start_datetime + timedelta(hours=x) for x in range(length)]
    
    # Generate some random data for 'y'
    data = np.random.randn(length)
    
    # Create a temporary DataFrame
    temp_df = pd.DataFrame({
        'unique_id': i,
        'ds': datetimes,
        'y': data
    })
    
    # Append the temporary DataFrame to the main DataFrame
    df = pd.concat([df, temp_df], ignore_index=True)

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
from statsforecast.utils import ConformalIntervals


sf = StatsForecast(
    models = [AutoARIMA(season_length = 12, prediction_intervals=ConformalIntervals(
            h=7,
            n_windows=3,
        ))],
    freq = 'M'
)

sf.fit(df)
sf.predict(h=12, level=[95])



```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @baniasbaabe, thanks for using statsforecast. The problem isn't the series lengths but the horizon of your intervals, it should either be 1 or match your forecasting horizon (12). In your example it says 2 but I'm pretty sure the error would be a mismatch between 7 (intervals' h) and 12 (forecast's h).

**Comment by baniasbaabe** [comment]
Oh okay, I guess this isn‘t the problem because the error will be raised when calling .fit(). So it doesn‘t care about the forecast horizon of the .predict() method.

**Comment by jmoralez** [comment]
Can you include the full stacktrace?

**Comment by baniasbaabe** [comment]
`ValueError                                Traceback (most recent call last)
[<ipython-input-3-d5b334ab18ae>](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in <cell line: 14>()
     12 )
     13 
---> 14 sf.fit(df)
     15 sf.predict(h=12, level=[95])

4 frames
[/usr/local/lib/python3.10/dist-packages/statsforecast/core.py](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in fit(self, df, sort_df, prediction_intervals)
    878         self._prepare_fit(df, sort_df)
    879         if self.n_jobs == 1:
--> 880             self.fitted_ = self.ga.fit(models=self.models)
    881         else:
    882             self.fitted_ = self._fit_parallel()

[/usr/local/lib/python3.10/dist-packages/statsforecast/core.py](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in fit(self, models)
     75             for i_model, model in enumerate(models):
     76                 new_model = model.new()
---> 77                 fm[i, i_model] = new_model.fit(y=y, X=X)
     78         return fm
     79 

[/usr/local/lib/python3.10/dist-packages/statsforecast/models.py](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in fit(self, y, X)
    362             )
    363 
--> 364         self._store_cs(y=y, X=X)
    365         return self
    366 

[/usr/local/lib/python3.10/dist-packages/statsforecast/models.py](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in _store_cs(self, y, X)
    133     def _store_cs(self, y, X):
    134         if self.prediction_intervals is not None:
--> 135             self._cs = self._conformity_scores(y, X)
    136 
    137     def _add_conformal_intervals(self, fcst, y, X, level):

[/usr/local/lib/python3.10/dist-packages/statsforecast/models.py](https://hbl3swyghvo-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231102-060217_RC00_578801940#) in _conformity_scores(self, y, X)
    124             )
    125             fcst_window = self.forecast(h=h, y=y_train, X=X_train, X_future=X_future)  # type: ignore[attr-defined]
--> 126             cs[i_window] = np.abs(fcst_window["mean"] - y_test)
    127         return cs
    128 

ValueError: operands could not be broadcast together with shapes (7,) (2,)`

**Comment by jmoralez** [comment]
Ah, in this case your series are too short. You're asking for 3 windows of size 7, which requires at least 22 samples, but you probably have series with less points than that. You can either remove those series or adjust the intervals settings.

**Comment by baniasbaabe** [comment]
Oh man, yes you are right. Didn‘t think about that. Now it‘s working fine. Thanks for the fast and helpful response!
