### ISSUE TITLE
[ARIMA] Incorrect computation of n 

### ISSUE THREAD

**Issue by jmoralez** [Nixtla/statsforecast#690]
### What happened + What you expected to happen

`n` here won't have the number of non NA values, but the number minus 1, because the end of the slice isn't included. This was originally reported in #654 since if there's a single sample then `n=0` and then we try to take its log.
https://github.com/Nixtla/statsforecast/blob/be9db750ab1fc858b6810f1395f36895a9e2f447/statsforecast/arima.py#L1212-L1214

### Versions / Dependencies

1.6.0

### Reproduction script

```python
import numpy as np
from statsforecast.models import AutoARIMA

AutoARIMA().fit(np.array([1.0]))
```

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @StatKumar. Sure, go ahead! We have a contributing guide [here](https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md) but feel free to ask any questions.

We also have the bug here: https://github.com/Nixtla/statsforecast/blob/be9db750ab1fc858b6810f1395f36895a9e2f447/statsforecast/arima.py#L1483-L1485
and here: https://github.com/Nixtla/statsforecast/blob/be9db750ab1fc858b6810f1395f36895a9e2f447/statsforecast/arima.py#L1815-L1817
The fix would be adding a +1 to the `lastnonmiss`, i.e. `lastnonmiss = missing_idxs.max() + 1` so that the last index is considered in the slice below.

**Comment by StatKumar** [comment]
Thank you @jmoralez
