### ISSUE TITLE
[Core] KaTex parse error: \tag works only in display equations

### ISSUE THREAD

**Issue by Azlich** [Nixtla/statsforecast#692]
### Description

I found some page's equations can't render. For example,

1. https://nixtla.mintlify.app/statsforecast/docs/models/arch.html
2. https://nixtla.mintlify.app/statsforecast/docs/models/arima.html
3. https://nixtla.mintlify.app/statsforecast/docs/models/autoces.html
4. https://nixtla.mintlify.app/statsforecast/docs/models/autoregressive.html
5. https://nixtla.mintlify.app/statsforecast/docs/models/autotheta.html

**Comment by jmoralez** [comment]
Hey @Azlich, thanks for raising this and https://github.com/Nixtla/hierarchicalforecast/issues/247. Sorry you had to run into those issues. We're working on fixing them.
