### ISSUE TITLE
[AutoARIMA] Inconsistent parameters between AutoARIMA and AutoARIMA inside StatsForecast 

### ISSUE THREAD

**Issue by Chaptyziok** [Nixtla/statsforecast#693]
### What happened + What you expected to happen

I have found a discrepancy in the parameters and predictions results when using the AutoARIMA model in two different ways: 
a) using AutoARIMA directly,
b) using AutoARIMA within the StatsForecast. 
I have simulated the data that shows this problem. Even though this issue does not occur with the majority of my time series there are several ones that show similar discrepancies in results.

### Versions / Dependencies

Python: 3.9.6
StatsForecast: 1.5.0

### Reproduction script
```python
import numpy as np
import pandas as pd
from statsforecast.core import StatsForecast
from statsforecast.models import AutoARIMA
from statsmodels.tsa.arima_process import ArmaProcess

# Simulated data
np.random.seed(42)
ar_params = np.array([0.5, -0.4, 0.3, 0.2, -0.1, 0.05])
ma_params = np.array([0.3, 0.1])
ar = np.r_[1, ar_params]
ma = np.r_[1, ma_params]
arma_process = ArmaProcess(ar, ma)
n_samples = 150
arima = arma_process.generate_sample(nsample=n_samples, scale=100)
period = 12
start_date = '2012-01-01'
dates = pd.date_range(start=start_date, periods=n_samples, freq='MS')
data = pd.DataFrame({
    'unique_id': 'Test',
    'ds': dates,
    'y': arima
})

# Forecasting with StatsForecast AutoARIMA
model = [AutoARIMA(season_length=period)]
model_statsforecast = StatsForecast(df=data, models=model, freq='MS')
fitted_statsforecast = model_statsforecast.fit(data)
predictions_statsforecast = model_statsforecast.predict(h=period).reset_index()
predictions_statsforecast.rename(columns={'AutoARIMA': 'StatsForecast_AutoARIMA'}, inplace=True)
params_statsforecast = fitted_statsforecast.fitted_[0][0].model_['arma']
coef_statsforecast = fitted_statsforecast.fitted_[0][0].model_['coef']

# Forecasting with AutoARIMA
y_series = data.set_index('ds')['y']
model_autoarima = AutoARIMA(season_length=period)
fitted_autoarima = model_autoarima.fit(y_series.values)
predictions = model_autoarima.predict(h=period)['mean']
prediction_dates = pd.date_range(start=y_series.index[-1] + pd.DateOffset(months=1), periods=period, freq='MS')
predictions_autoarima = pd.DataFrame({
    'unique_id': 'Test',
    'ds': prediction_dates,
    'AutoARIMA': predictions})
params_autoarima = fitted_autoarima.model_['arma']
coef_autoarima = fitted_autoarima.model_['coef']

# Error calculation
comparison = pd.merge(predictions_statsforecast, predictions_autoarima, on=['unique_id', 'ds'])
comparison['error'] = comparison['StatsForecast_AutoARIMA'] - comparison['AutoARIMA']
error = comparison.groupby('unique_id')['error'].sum().reset_index()

# Results
print(error)
print("Parameters from StatsForecast AutoARIMA:", params_statsforecast)
print("Coefficients from StatsForecast AutoARIMA:", coef_statsforecast)
print("Parameters from AutoARIMA:", params_autoarima)
print("Coefficients from AutoARIMA:", coef_autoarima)
```
### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @Chaptyziok, thanks for using statsforecast and for the excellent report. I ran your example and I get a very small difference. Is that what you're getting as well?
![image](https://github.com/Nixtla/statsforecast/assets/8473587/2d6cafbe-16a0-49f4-9b4e-15a3745450c6)

**Comment by Chaptyziok** [comment]
I think it would be better to check this data, since the arma process can be random. So for the data in the attachment I got:
``
  unique_id      error
0      Test  17.717997
Parameters from StatsForecast AutoARIMA: (3, 2, 0, 0, 1, 0, 0)
Coefficients from StatsForecast AutoARIMA: {'ar1': -0.2597657642127478, 'ar2': -0.0766643823245807, 'ar3': -0.48625037863973297, 'ma1': -0.002987491075429605, 'ma2': 0.5414472166606323}
Parameters from AutoARIMA: (5, 0, 0, 0, 1, 0, 0)
Coefficients from AutoARIMA: {'ar1': -0.2490511794010501, 'ar2': 0.4820996537867249, 'ar3': -0.4206488947374526, 'ar4': -0.2006340807440009, 'ar5': 0.2672321004566039}
``
[data_arima.csv](https://github.com/Nixtla/statsforecast/files/13339901/data_arima.csv)

**Comment by jmoralez** [comment]
I get this with that data. Can you try upgrading to 1.6.0?
```
  unique_id         error
0      Test  9.283732e-07
Parameters from StatsForecast AutoARIMA: (4, 1, 0, 0, 1, 0, 0)
Coefficients from StatsForecast AutoARIMA: {'ar1': -0.7499653632462349, 'ar2': 0.30081724110142866, 'ar3': -0.19239378652879252, 'ar4': -0.41796540194747045, 'ma1': 0.4769590728528615}
Parameters from AutoARIMA: (4, 1, 0, 0, 1, 0, 0)
Coefficients from AutoARIMA: {'ar1': -0.7499653632462349, 'ar2': 0.30081724110142866, 'ar3': -0.19239378652879252, 'ar4': -0.41796540194747045, 'ma1': 0.4769590728528615}

```

**Comment by Chaptyziok** [comment]
It works after the Statsforecast upgrade. Thank you very much.
