### ISSUE TITLE
Models: How does AutoARIMA, AutoETS, etc. handle future covariates

### ISSUE THREAD

**Issue by negodfre** [Nixtla/statsforecast#702]
### Description

I was looking for how future covariates are handled mathematically.
I see Rob Hyndman has mentioned a few ways these can get incorporated into ARIMA:

https://robjhyndman.com/hyndsight/arimax/

Is nixtla AutoARIMA using SARIMAX, Regression with SARIMA errors, or a Transfer function?

**Comment by jmoralez** [comment]
Hey. It's a regression with SARIMA errors.
