### ISSUE TITLE
Autoets forecast Feature  suggestions

### ISSUE THREAD

**Issue by vatsmanish** [Nixtla/statsforecast#719]
### Description

Hello Team ,
I would like to raise one of  feature request in the AutoETS   when we use . fit method we get forecast. but as we know we are passing multiple combinantion of model(e.g-(A,A,N),(M,A,N),(M,N,N)).
![auto ets fit](https://github.com/Nixtla/statsforecast/assets/40766378/cf01381a-2b30-4aab-ae36-21db2b632d99)
Now in the .fit method  i have not specify any specific model , how would i see which of the above mentioned model has been selected??

**Example:- I have passed 10 unique id in my model how would i figure out which unique id has selected what type of model has been fitted?**
![forecast_auto ets](https://github.com/Nixtla/statsforecast/assets/40766378/127e1972-0bf9-435d-b6a7-431d67f7b532)

### Use case

This feature will helps to enhance   the model Interpretability and business to interpret the forecast. From this feature  we can explain  for different unique id which model has been selected  and what will be there significance importance of this model?

**Comment by jmoralez** [comment]
Hey. When you call the fit method the models are stored in the `fitted_` attribute, which is an array of shape (n_series, n_models). So for example you can get the model that was trained with the following:
```python
from statsforecast import StatsForecast
from statsforecast.models import AutoETS
from statsforecast.utils import generate_series

series = generate_series(5, freq='M')
sf = StatsForecast(
    models=[AutoETS(season_length=12)],
    freq='M',
)
sf.fit(series)
fitted_ets = sf.fitted_[:, 0]  # first column here since it's the first model in the models list
model_by_id = {uid: m.model_['method'] for uid, m in zip(sf.uids, fitted_ets)}
```
