### ISSUE TITLE
API Reference/ Models not loading

### ISSUE THREAD

**Issue by osmanezgi** [Nixtla/statsforecast#722]
### Description

I'd like to reach the model documentation under the API Reference section ([link](https://nixtlaverse.nixtla.io/statsforecast/src/core/models.html)), however, I keep getting 500 error on the page. It is not reachable in the last few days I've tried. I am using statsforecast for my thesis and need to reach the detailed documentation to cite and use the information. Sharing the error page below:

![image](https://github.com/Nixtla/statsforecast/assets/85928028/29939e3a-8893-4c83-86bd-9a8a0fb0db70)

Thank you very much!

### Link

https://nixtlaverse.nixtla.io/statsforecast/src/core/models.html

**Comment by jmoralez** [comment]
Reopening since it's still broken.

**Comment by jmoralez** [comment]
Fixed by #724
