### ISSUE TITLE
How to stop Jupyter Notebook Python kernel crashing when calling "from statsforecast.adapters.prophet import AutoARIMAProphet"?

### ISSUE THREAD

**Issue by Josepancho** [Nixtla/statsforecast#729]
### Discussed in https://github.com/Nixtla/statsforecast/discussions/728

<div type='discussions-op-text'>

<sup>Originally posted by **Josepancho** December 16, 2023</sup>
Has anyone encountered this problem with Jupyter notebook python kernel crashing when trying to call "from statsforecast.adapters.prophet import AutoARIMAProphet?

I am using Python 3.11 and I successfully installed statsforecast version 1.6.0. I would like to use the statesforecast adopter for Prophet. Any help, please?</div>

**Comment by jmoralez** [comment]
Hey. Are you able to import just prophet, e.g. `from prophet import Prophet`?
