### ISSUE TITLE
StatsForecast Constructor Does Not Accept Polars Dataframe

### ISSUE THREAD

**Issue by MathisC22** [Nixtla/statsforecast#738]
### What happened + What you expected to happen

After updating StatsForecast from 1.6 to 1.7, I noticed that my ARIMA module would not run anymore. When initializing a new StatsForecast object with a polars dataframe for argument `df`, I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/.venv/lib/python3.10/site-packages/statsforecast/core.py", line 520, in __init__
    self._prepare_fit(df=df, sort_df=sort_df)
  File "/app/.venv/lib/python3.10/site-packages/statsforecast/core.py", line 549, in _prepare_fit
    validate_freq(df[time_col], self.freq)
  File "/app/.venv/lib/python3.10/site-packages/utilsforecast/validation.py", line 151, in validate_freq
    raise ValueError(
ValueError: You must specify a valid polars offset when using polars dataframes. You can find the available offsets in https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.dt.offset_by.html
```

It works, however, if I transform the polars dataframe to a pandas dataframe, i.e. `StatsForecast(df=df.to_pandas(), ...)`.

### Versions / Dependencies

Python 3.10.13
StatsForecast 1.7.0
Polars 0.19.19
Windows 10

### Reproduction script

```python
import polars as pl 
from statsforecast import StatsForecast
from statsforecast.models import ARIMA

df = pl.DataFrame({
    'ds': ['2014-06-01', '2014-07-01', '2014-08-01', '2014-09-01'],
    'y': [118.0, 116.9, 116.6, 116.6],
    'unique_id': [1, 1, 1, 1]
})
df = df.with_columns(pl.col("ds").str.to_date())

models = [ARIMA(order=(1, 0, 0), season_length=12, include_constant=True)]
sf = StatsForecast(df=df , models=models, freq="MS", n_jobs=1)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey. As the error states you must provide a valid polars offset, e.g. '1mo'

**Comment by jmoralez** [comment]
You should've also got a deprecation warning, please provide the df to the corresponding method (fit, forecast) instead of the constructor.

**Comment by MathisC22** [comment]
Hey @jmoralez, thanks for your quick response! I totally forgot that those frequency strings were pandas-specific and not something that is standardized across Python. Interestingly, a deprecation warning did (and does) not occur. A quick research tells me that this is the case because [deprecation warnings are ignored by default](https://docs.python.org/3/library/warnings.html#default-warning-filter) for code not directly called in `__main__`. Since I use StatsForecast in my actual code inside a class that gets called during a pipeline, the warning never popped up.

**Comment by jmoralez** [comment]
Thanks a lot for that reference, I somehow missed it when choosing between Future vs Deprecation warnings. We've changed them to FutureWarning so they should pop up in the next release.
