### ISSUE TITLE
plot is not showing as per as the doc mention

### ISSUE THREAD

**Issue by neonarc4** [Nixtla/statsforecast#748]
### What happened + What you expected to happen

fig = sf.plot(df, forecast_df, level=[90])
print(fig)  # Figure(2400x350)

### Versions / Dependencies

newest   and window 11 python 10

### Reproduction script

```

from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
import pandas as pd
df = pd.read_csv("https://datasets-nixtla.s3.amazonaws.com/air-passengers.csv", parse_dates=["ds"])

df.head()

sf = StatsForecast(
    models=[AutoARIMA(season_length=12)],
    freq="M",
)

sf.fit(df)
forecast_df = sf.predict(h=12, level=[90])
forecast_df.tail()
fig = sf.plot(df, forecast_df, level=[90])
print(fig)
```

### Issue Severity

High: It blocks me from completing my task.

**Comment by jmoralez** [comment]
Hey @neonarc4, thanks for using statsforecast. The plot method returns a matplotlib figure, which you can't print. If you're running a script you can save it like this:
```python
fig = sf.plot(df, forecast_df, level=[90])
fig.savefig('myfigure.png')
```
and then open it.

If you're using jupyter you can just run `fig` and it will be displayed.

**Comment by neonarc4** [comment]
@jmoralez  i have certain issue using this ds time it always say me
 
PlotFigure.js?t=1704461326399:11 Warning: some data associated with the x scale are dates. Dates are typically associated with a "utc" or "time" scale rather than a "band" scale. If you are using a bar mark, you probably want a rect mark with the interval option instead; if you are using a group transform, you probably want a bin transform instead. If you want to treat this data as ordinal, you can specify the interval of the x scale (e.g., d3.utcDay), or you can suppress this warning by setting the type of the x scale to "band".

new Date('2024-01-06 01:58:36')
i am trying to apply this timezone but it getting me a failure on plotjs do u know why

**Comment by neonarc4** [comment]
thnx bro what is session length and level do ?

**Comment by mergenthaler** [comment]
Hi @neonarc4 thanks for using StatsForecast.

The "seasonality length" parameter refers to the number of time periods it takes for a full seasonal cycle to complete in your data. Eg:

| Data Frequency | Seasonality Length | Description                        |
|----------------|--------------------|------------------------------------|
| Monthly        | 12                 | Yearly cycle (12 months in a year)  |
| Quarterly      | 4                  | Yearly cycle (4 quarters in a year)|
| Weekly         | 52                 | Yearly cycle (52 weeks in a year)  |
| Daily          | 7                  | Weekly cycle                       |
| Hourly         | 24                 | Daily cycle                        |

Level refers to prediction intervals. See: https://nixtlaverse.nixtla.io/statsforecast/docs/tutorials/uncertaintyintervals.html

**Comment by neonarc4** [comment]
@mergenthaler  sorry for troubling u got little fever earlier

what does the level do  sf.predict(level=[90])

and why i get this type of prediction what can i do to make it better ? 
![image](https://github.com/Nixtla/statsforecast/assets/140290288/3589a7ca-8d9a-40fe-b286-a9ab3f163ec9)
