### ISSUE TITLE
Croston: Error fitting with 0.0 values

### ISSUE THREAD

**Issue by dgarridoa** [Nixtla/statsforecast#772]
### What happened + What you expected to happen

Croston models are not supporting 0.0 values. Before this [PR](https://github.com/Nixtla/statsforecast/commit/7e69091f7315b061f63eff03df1acf1de7e2c8b4#diff-d7fe88bcec62cd796700d50b77d523c59a5854900ad6ff2baac97ff004eae311) it was possible.

The error is caused by `self.model_["sigma"] = _calculate_sigma(y - self.model_["fitted"], y.size)`, where `y` has size `len(y)` and `self.model_["fitted"]` has size `len(y[y > 0])`. This can be found, for instance, in line the line 4056 from the file `statsforecast/models.py`.

### Versions / Dependencies

python 3.10.11
statsforecast 1.7.2
ubuntu 23.04

### Reproduction script

Steps to reproduce the error:

```python
import numpy as np
from statsforecast.models import CrostonClassic

y = np.random.random(0, 100)
y[-1] = 0.0
model = CrostonClassic()
model.fit(y)


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dgarridoa/Desktop/opensource/statsforecast/statsforecast/models.py", line 4054, in fit
    self.model_["sigma"] = _calculate_sigma(y - self.model_["fitted"], y.size)
ValueError: operands could not be broadcast together with shapes (100,) (99,)
```

Downgrading to version 1.7.1 solves the problem.

```
 model.predict(2)
{'mean': array([0.31759617, 0.31759617], dtype=float32)}
```

### Issue Severity

High

**Comment by jmoralez** [comment]
Hey @dgarridoa, thanks for the report. We'll work on a fix soon.
