### ISSUE TITLE
Typos in arima.ipynb

### ISSUE THREAD

**Issue by ThomasBourgeois** [Nixtla/statsforecast#78]
Several typos in the notebook : 
- 'Would nn autorregresive '
- 'testing purporses,'
- 'will let auto_arima to handle'

**Comment by baggiponte** [comment]
just to make sure, you mean [here](https://github.com/Nixtla/statsforecast/blob/main/nbs/arima.ipynb) right?

**Comment by ThomasBourgeois** [comment]
nope I meant [there](https://github.com/Nixtla/statsforecast/blob/main/examples/arima.ipynb)

**Comment by baggiponte** [comment]
Hi, sorry for the late reply. I clicked on your link and I get a 404 error - was this solved already? I would like to contribute.

**Comment by FedericoGarza** [comment]
Hi @baggiponte @ThomasBourgeois. The notebook was renamed: https://github.com/Nixtla/statsforecast/blob/main/nbs/examples/AutoArima_vs_Prophet.ipynb.

Instructions on how to contribute can be found here: https://github.com/Nixtla/statsforecast/blob/main/CONTRIBUTING.md

:)

**Comment by baggiponte** [comment]
Went through the notebook and did not find any typos!

**Comment by kvnkho** [comment]
Closing due to staleness doc changes. We can revive the issue if typos are found here: https://nixtla.github.io/statsforecast/docs/how-to-guides/autoarima_vs_prophet.html
