### ISSUE TITLE
Allow external regressors TBATS

### ISSUE THREAD

**Issue by juanitorduz** [Nixtla/statsforecast#780]
### Description

It seems the current TBATS implementation does not allow external regressors. Still, I think (maybe I am wrong 🙈 ) that it should be "easy" as we need to pass `X` here https://github.com/Nixtla/statsforecast/blob/main/statsforecast/tbats.py#L875 into the [`auto_arima_f`](https://github.com/Nixtla/statsforecast/blob/main/statsforecast/arima.py#L1817) as this function already have and `xreg` argument. Do you think it is that simple? If so, I could open a PR.

### Use case

Having the availability of including external regressors can be very useful for real applications.

**Comment by candalfigomoro** [comment]
https://robjhyndman.com/hyndsight/tbats-with-regressors/

**Comment by juanitorduz** [comment]
Thank you for pointing that out! It makes sense :) . It would be great to have these observations in the docs 😄! I'll close this issue then.
