### ISSUE TITLE
can we reduce the prediction accuracy 

### ISSUE THREAD

**Issue by neonarc4** [Nixtla/statsforecast#782]
i want to reduce it compile time 

i am using arima

**Comment by jmoralez** [comment]
Hey @neonarc4, thanks for using statsforecast. What do you mean by "reduce the prediction accuracy"? If you want to reduce the compile time you can try [caching](https://nixtlaverse.nixtla.io/statsforecast/docs/how-to-guides/numba_cache.html) and if that's the case please update the issue title.

**Comment by neonarc4** [comment]
moment

**Comment by neonarc4** [comment]
@jmoralez  i tried it does improve it speed but i want need more speed i want to lose some prediction accuracy

**Comment by neonarc4** [comment]
```
os.environ["NIXTLA_NUMBA_CACHE"] = 1
os.environ["NUMBA_CACHE_DIR"] = 'numba_cache'
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA

sf = StatsForecast(
    models=[AutoARIMA(season_length = 12)],
    freq='M',
)

sf.fit(df)
```

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/a25fdae6-4a02-4b01-9692-57943c204698) @jmoralez

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/e565b191-1c27-449c-a979-d26c0bab870f)

**Comment by jmoralez** [comment]
Which version of statsforecast are you using?

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/28e962b8-0aed-4158-a52e-1e85add67002)

**Comment by jmoralez** [comment]
statsforecast doesn't support GPU acceleration

**Comment by neonarc4** [comment]
> statsforecast doesn't support GPU acceleration

ah but something horrible just happen me right now can u help i bymistake mess up with path and then my python stuck at 3.11

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/480be56a-8cc2-4f8a-902c-ea43545ab6f9)
how can i fix it ?

**Comment by neonarc4** [comment]
ah lol then how can i fix this caching issue?

**Comment by jmoralez** [comment]
Which version of statsforecast are you using?

**Comment by neonarc4** [comment]
1.7.0

**Comment by neonarc4** [comment]
@jmoralez  
```
from statsforecast import StatsForecast
from statsforecast.models import AutoARIMA
import pandas as pd
import os

os.environ["NIXTLA_NUMBA_CACHE"] = "1"
os.environ["NUMBA_CACHE_DIR"] = "X:/sad/practice/test/aii/data"
df = pd.read_csv("https://datasets-nixtla.s3.amazonaws.com/air-passengers.csv", parse_dates=["ds"])

df.head()

sf = StatsForecast(
    models=[AutoARIMA(season_length=12)],
    freq="M",
)

sf.fit(df)
forecast_df = sf.predict(h=12, level=[90])
forecast_df.tail()
fig = sf.plot(df, forecast_df, level=[90])
fig.savefig("myfigure.png")

```

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/dafd97f6-e660-4888-97ff-0234fac7480a)

**Comment by jmoralez** [comment]
> os.environ["NUMBA_CACHE_DIR"] = "X:/sad/practice/test/aii/data"

I don't think that's a valid path in Windows, it should probably be something like: "X:\\sad\\practice\\test\\aii\\data"`. You can also not set this variable and just use the default directory (__pycache__)

**Comment by neonarc4** [comment]
in window generally we do / instead of \

**Comment by neonarc4** [comment]
i dont think it was working on window

**Comment by neonarc4** [comment]
@jmoralez 
![image](https://github.com/Nixtla/statsforecast/assets/140290288/3136c8cc-a0f9-4054-821b-5b9bdb514a5a)

**Comment by neonarc4** [comment]
plz guide me bro

**Comment by jmoralez** [comment]
You can set the `NUMBA_DEBUG_CACHE` env variable to see where the cache is being saved. Here's a minimal example:

```python
import os

from numba import njit

os.environ['NUMBA_DEBUG_CACHE'] = '1'

@njit(cache=True)
def f(x):
    return x + 1

print(f(1))
```
running this script I get:
```
[cache] index saved to 'C:\\Users\\MyUser\\__pycache__\\test.f-7.py310.nbi'
[cache] data saved to 'C:\\Users\\MyUser\\__pycache__\\test.f-7.py310.1.nbc'
2
```

**Comment by neonarc4** [comment]
sorry fell sleep

**Comment by neonarc4** [comment]
![image](https://github.com/Nixtla/statsforecast/assets/140290288/6e89b531-52c0-4828-8ed3-4a2021117e8d)
ur code work but when i put it on statsforccast it doesnt

**Comment by jmoralez** [comment]
Can you set the env variable before importing statsforecast?

**Comment by neonarc4** [comment]
i love u bro amazing >.</
