### ISSUE TITLE
MSTL Plot

### ISSUE THREAD

**Issue by firmai** [Nixtla/statsforecast#787]
### Description

It would be lovely if you could develop a decomposition plot 
![image](https://github.com/Nixtla/statsforecast/assets/26666267/86e4013d-fd55-4656-a369-e1d08dba2381)

**Comment by jmoralez** [comment]
Hey @firmai, thanks for using statsforecast. We don't have a built-in way to do this but it's straightforward to do, here's an example:
```python
import numpy as np
from statsforecast.models import MSTL

# generate serie
amplitudes = [3, 5]
seasonal_periods = [5, 24]
t = 1 + np.arange(500)
x = np.random.normal(scale=0.1, size=t.size)
for amplitude, period in zip(amplitudes, seasonal_periods):
    x += amplitude * np.cos(2 * np.pi * t / period)

model = MSTL(season_length=seasonal_periods).fit(x)
model.model_.plot(subplots=True);
```
which yields the following
![image](https://github.com/Nixtla/statsforecast/assets/8473587/bcbd79ad-69f5-49ec-acd1-c0a838931d45)

If you're using `sf = StatsForecast(...).fit(...)` the models are available in `sf.fitted_`, so you could extract the first model with `sf.fitted_[0, 0].model_` (assuming MSTL is the first model in your list).
