### ISSUE TITLE
Nixtla statsforecast/statsmodels failing to import polars

### ISSUE THREAD

**Issue by kleofas97** [Nixtla/statsforecast#792]
### What happened + What you expected to happen

Hi,
There's a bug in installing statsforecast with dependency `polars`. While pip installing  `statsmodels==0.13.5`, downloaded version of polars does not have an attribute _cpu_check. This makes the import failing.
![image](https://github.com/Nixtla/statsforecast/assets/34525220/04409018-9625-43ad-b930-3d6579787511)

The behaviour was spotted in databricks, while istalling statsmodels today in the morning (yesterday it worked).

You can fix it by specifiing version of polars, in our case it was `polars==0.20.5`. I believe the issue is related with not specifing version of polars that you are using. 

### Versions / Dependencies

python==3.9.5
statsmodels==0.13.5
platform - databricks 12.2

### Reproduction script

pip install statsmodels==0.13.5

### Issue Severity

None

**Comment by kleofas97** [comment]
It's possible it will be fixed by polars, but anyway this seems to be a vulerability on your side to not have the version specified

**Comment by jmoralez** [comment]
Hey @kleofas97. polars is an optional a dependency of statsforecast, so if you `pip install statsforecast` you won't get it, you'd have to use `pip install statsforecast[polars]`. statsmodels doesn't depend on polars either, so I'm a bit confused on how you got it.
