### ISSUE TITLE
Independency of Time Series with Different Unique IDs

### ISSUE THREAD

**Issue by furkancanturk** [Nixtla/statsforecast#796]
Hi,
I have a general question about interdependecy/dependency of multiple time series inputted to StatsForecast or MLForecast or NeuralForecast objects.

I have two time series with unique_id = {1, 2}. Assume we use only StatsForecast. I train models with the following approaches.

1) I inputted the dataframe comprised of both time series (maintaining their unique_ids) to a single StatsForecast object.
2) I inputted each dataframe comprised of only one time series to separate StatsForecast objects.

The predictions from the single StatsForecast (1) differ than that of the separate StatsForecast objects (2) for each time series. Why? Is not supposed that time series with unique IDs are independent of each other during the training and the predictions obtained with both implementations must be the same?

**Comment by jmoralez** [comment]
Hey @furkancanturk. Can you please provide a reproducible example?

**Comment by furkancanturk** [comment]
I've figured out that my raw dataframe (of a hierarchical dataset) includes null values in some columns used for hierarchy levels. Thus,  `aggregate` func in hierarchicalforecast results in different time-series at top levels when I change the hierarchy depth. So, the problem is irrelavant to what I asked and no problem detected in the libraries. Thanks for your time.
