### ISSUE TITLE
Missing Amazon Forecast results in the experiment docs

### ISSUE THREAD

**Issue by arianmaghsoudnia** [Nixtla/statsforecast#804]
Hi there,
I was checking the interesting experiment you have done comparing StatsForecast vs Amazon Forecast [here](https://github.com/Nixtla/statsforecast/tree/main/experiments/amazon_forecast).
However, the link to [reproduce the results](https://nixtla.github.io/statsforecast/examples/aws/statsforecast.html) is not working anymore.  I found a documentation [here](https://nixtlaverse.nixtla.io/statsforecast/docs/experiments/amazonstatsforecast.html) that I believe it should refer to.
Then I could fetch the forecast results for the StatsForecast but not for the Amazon Forecast S3 ( on s3://m5-benchmarks/forecasts/amazonforecast-m5.parquet).
```
Exception has occurred: OSError
When getting information for key 'forecasts/amazonforecast-m5.parquet' in bucket 'm5-benchmarks': AWS Error ACCESS_DENIED during HeadObject operation: No response body.
  File ...
    amazonforecasts_df = pd.read_parquet(
                         ^^^^^^^^^^^^^^^^
OSError: When getting information for key 'forecasts/amazonforecast-m5.parquet' in bucket 'm5-benchmarks': AWS Error ACCESS_DENIED during HeadObject operation: No response body.
```
Can you please check if the file is available and accessible?

**Comment by jmoralez** [comment]
Hey. They're both in the same (public) bucket, so you should be able to read them both. Can you try adding `storage_options={"anon": True}`? i.e. change the read command to `amazonforecasts_df = pd.read_parquet('s3://m5-benchmarks/forecasts/amazonforecast-m5.parquet', storage_options={"anon": True})`

**Comment by jmoralez** [comment]
I just thought about this a bit more and I think that since the amazon forecasts results were a directory they required you to have permission to list the bucket, which you most likely don't have. I just concatenated the results into a single file (with the same name) so you should now be able to read it. Please let us know if you run into any more issues.

**Comment by arianmaghsoudnia** [comment]
This solved the issue. Thanks!
