### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'n_windows' when adding confidence level

### ISSUE THREAD

**Issue by Hailey-ww** [Nixtla/statsforecast#805]
Encountering the following issue when using StatsForecast for anomaly detection:
When setting horizon = 48 and levels = [99], and executing the following code:

fcst = sf.forecast(h=48, level=[99], fitted=True)
fcst = fcst.reset_index()
fcst.head()

It results in the following error:

AttributeError: 'bool' object has no attribute 'n_windows'

**Comment by jmoralez** [comment]
Hey @Hailey-ww, thanks for using statsforecast. Can you please provide a minimal reproducible example? You're not showing how you initialize the StatsForecast object, which data you're using, the stacktrace, etc.

**Comment by Hailey-ww** [comment]
> Hey @Hailey-ww, thanks for using statsforecast. Can you please provide a minimal reproducible example? You're not showing how you initialize the StatsForecast object, which data you're using, the stacktrace, etc.

Here it is. I copied the given sample code to test. Thanks.
![WechatIMG766](https://github.com/Nixtla/statsforecast/assets/63403668/c0dad61e-1979-42f5-bb8a-d4f0d4aee4dd)
![WechatIMG768](https://github.com/Nixtla/statsforecast/assets/63403668/1a74a8c7-4b9a-4cb8-92fb-cf68b8432b49)
![WechatIMG769](https://github.com/Nixtla/statsforecast/assets/63403668/41343568-ac23-4179-83be-0e7f7e354b12)

**Comment by jmoralez** [comment]
We dropped support for python 3.7 a couple of versions ago. Can you try upgrading to python 3.8 and using the latest version?
