### ISSUE TITLE
ARIMA model parameters

### ISSUE THREAD

**Issue by ngupta23** [Nixtla/statsforecast#83]
While `AutoARIMA` from `pmdarima` is slow, it shows the model hyperparameters in a convenient manner. How can I get the same for `statsforecast` `AutoARIMA`?

A consistent interface with `pmdarima` (as much as possible) would be appreciated so it can be a drop in replacement.

![image](https://user-images.githubusercontent.com/33585645/161104766-4200b4af-5bed-4b4a-9317-c7bb55faaedb.png)

**Comment by FedericoGarza** [comment]
Hi @ngupta23! We just released the [v0.5.3](#91) of `StatsForecast` that includes a representational string of the model. :) We followed the R convention. 
<img width="392" alt="image" src="https://user-images.githubusercontent.com/10517170/163036108-dcaf375d-5e6b-46fe-b4cf-b5bd4256460e.png">

Please let us know what you think and if you have more feature requests.

**Comment by ngupta23** [comment]
Thanks @FedericoGarza I will play around with it and let you know if any other alignment is needed with pmdarima. 
I am assuming that `get_param`s will work in sktime when using this model?

Also, does it provide a statictical summary such as that obtained from pmdarima `summary()` method?

Thanks

**Comment by mspinelli** [comment]
> Hi @ngupta23! We just released the [v0.5.3](#91) of `StatsForecast` that includes a representational string of the model. :) We followed the R convention. <img alt="image" width="392" src="https://user-images.githubusercontent.com/10517170/163036108-dcaf375d-5e6b-46fe-b4cf-b5bd4256460e.png">
> 
> Please let us know what you think and if you have more feature requests.

The only way I can figure out how to see the params is to set `models=[AutoARIMA(trace=True)]`. However, I'd like to be able to access the parameters programmatically so that I can then run statsmodels's SARIMAX and see the diagnostics and print a summary without having to manually type in the p, d, q and seasonal parameters.
