### ISSUE TITLE
Problem using fit and predict or fit_predict using a spark dataframe

### ISSUE THREAD

**Issue by Jonathan-87** [Nixtla/statsforecast#832]
### What happened + What you expected to happen

When using a spark dataframe and we use statsforecast fit then predict method or fit_predict method then we obtain an error "AttributeError: 'NoneType' object has no attribute 'Date'". Note that we don't have this error if we use the statsforecast forecast method.

### Versions / Dependencies

statsforecast 1.7.4

### Reproduction script

import datetime as dt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsforecast.utils import AirPassengersDF
from statsforecast import StatsForecast
from statsforecast.models import AutoETS

#Using fit then predict method

models = [AutoETS(season_length=12)]

sf = StatsForecast(
    models=models, 
    freq='M',
    verbose=True,
    n_jobs=-1
)

horizon = 12
n_windows = 5

#Convert to Spark, partition by unique_id and persist the data
spk_df = spark.createDataFrame(AirPassengersDF)
spk_df = spk_df.repartition("unique_id")
spk_df.cache().persist()

sf.fit(
    df=spk_df,
    id_col="unique_id",
    time_col="ds",
    target_col="y"
)

results = sf.predict(    
    h=horizon,
    level=[80, 90]
).toPandas()

#Using fit_predict method

models = [AutoETS(season_length=12)]

sf = StatsForecast(
    models=models, 
    freq='M',
    verbose=True,
    n_jobs=-1
)

horizon = 12
n_windows = 5

#Convert to Spark, partition by unique_id and persist the data
spk_df = spark.createDataFrame(AirPassengersDF)
spk_df = spk_df.repartition("unique_id")
spk_df.cache().persist()

results = sf.fit_predict(
    df=spk_df,
    h=horizon,
    level=[80, 90],
    id_col="unique_id",
    time_col="ds",
    target_col="y"
).toPandas()

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @Jonathan-87, those methods aren't supported in distributed. Only forecast and cross_validation ([ref](https://nixtlaverse.nixtla.io/statsforecast/src/core/distributed.fugue.html)) are supported.
