### ISSUE TITLE
Model evaluation documentation asserts that datasetsforecast is required, but it isn't

### ISSUE THREAD

**Issue by quant5** [Nixtla/statsforecast#833]
### Description

In many of the "Model Evaluation" sections within the `statsforecast` docs, it's mentioned that `datasetsforecast` is a required installation in order to get access to error metrics.

However, this is not the case, as one can simply import them from `utilsforecast`, which comes installed with `statsforecast`.

```
from utilsforecast.losses import *
```

My sense is that the docs would read cleaner without this additional unnecessary external install requirement. Let me know what you think.

### Link

https://nixtlaverse.nixtla.io/statsforecast/docs/models/autoarima.html#model-evaluation
https://nixtlaverse.nixtla.io/statsforecast/docs/models/optimizedtheta.html#model-evaluation

And others.

**Comment by jmoralez** [comment]
I think this is closely related to #834 and would be fixed by it, should we close this one?
