### ISSUE TITLE
MSTL can't use AutoETS as trend_forecaster

### ISSUE THREAD

**Issue by sm-ak-r33** [Nixtla/statsforecast#840]
### What happened + What you expected to happen

When I try MSTL with AutoArima it works, but it does not work with AutoETS

 "Exception: Trend forecaster should not adjust seasonal models." 
 
 

### Versions / Dependencies

Python 3.8- AzureML

### Reproduction script

from statsforecast.models import MSTL, AutoETS

models = [MSTL(
    season_length=[12], # seasonalities of the time series 
    trend_forecaster=AutoETS() # model used to forecast trend
)]
sf = StatsForecast(
    models=models, # model used to fit each time series 
    freq='M', # frequency of the data
    )

sf = sf.fit(df=df_monthly)
#sf.fitted_[0, 0].model_
forecasts_monthly_ets = sf.predict(h=12)

when I try to run this thing I get the following error saying 

"Exception: Trend forecaster should not adjust seasonal models."

### Issue Severity

None

**Comment by jmoralez** [comment]
Hey @sm-ak-r33, thanks for using statsforecast. `AutoETS` is actually the default `trend_forecaster`, you just need to disable the seasonal period by setting its search space to `"ZZN"` (choose best error type, choose best trend type, no seasonal component).
 https://github.com/Nixtla/statsforecast/blob/ab573b4267cf2332ca89322da6ad0b25a35c7ce6/statsforecast/models.py#L5084
