### ISSUE TITLE
statsforecast: prediction fails if more than one model uses fallbackheuristic

### ISSUE THREAD

**Issue by EddyXorb** [Nixtla/statsforecast#845]
### What happened + What you expected to happen

1. I trained monthly data, that had only 3 months with the following code:
```python 
strategies = [
    AutoRegressive(lags=[1, 2, 11, 12, 13], alias="ARLags1_2_11_12_13"),
    HoltWinters(season_length=12, alias="VERYDIFFERENT"),
    SeasonalNaive(season_length=12),
]

  sf = StatsForecast(
        models=strategies,
        freq="1mo",
        n_jobs=-1,
        fallback_model=HistoricAverage(),
        verbose=True,
    )

fit_result = sf.fit(df=train_data)
```
Then I predicted with:

```python
prediction = fit_result .predict(h=12, X_df=test_data.drop("y"))
```
which fails with the following output:

> ComputeError                              Traceback (most recent call last)
> Cell In[85], [line 6](vscode-notebook-cell:?execution_count=85&line=6)
> ----> [6](vscode-notebook-cell:?execution_count=85&line=6) prediction = fit_result .predict(h=12, X_df=test_data.drop("y"))
>       [7](vscode-notebook-cell:?execution_count=85&line=8) )
> 
> File c:\Code\arbeit\mathtec\adlerlacke\.venv\Lib\site-packages\statsforecast\core.py:741, in _StatsForecast.predict(self, h, X_df, level)
>     [739](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/statsforecast/core.py:739)     fcsts, cols = self._predict_parallel(h=h, X=X, level=level)
>     [740](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/statsforecast/core.py:740) fcsts_df = self._make_future_df(h=h)
> --> [741](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/statsforecast/core.py:741) fcsts_df[cols] = fcsts
>     [742](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/statsforecast/core.py:742) return fcsts_df
> 
> File c:\Code\arbeit\mathtec\adlerlacke\.venv\Lib\site-packages\polars\dataframe\frame.py:1209, in DataFrame.__setitem__(self, key, value)
>    [1207](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:1207)     for i, name in enumerate(key):
>    [1208](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:1208)         columns.append(pl.Series(name, value[:, i]))
> -> [1209](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:1209)     self._df = self.with_columns(columns)._df
>    [1211](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:1211) # df[a, b]
>    [1212](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:1212) elif isinstance(key, tuple):
> 
> File c:\Code\arbeit\mathtec\adlerlacke\.venv\Lib\site-packages\polars\dataframe\frame.py:7874, in DataFrame.with_columns(self, *exprs, **named_exprs)
>    [7728](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7728) def with_columns(
>    [7729](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7729)     self,
>    [7730](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7730)     *exprs: IntoExpr | Iterable[IntoExpr],
>    [7731](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7731)     **named_exprs: IntoExpr,
>    [7732](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7732) ) -> DataFrame:
>    [7733](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7733)     """
>    [7734](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7734)     Add columns to this DataFrame.
>    [7735](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7735) 
>    (...)
>    [7872](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7872)     └─────┴──────┴─────────────┘
>    [7873](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7873)     """
> -> [7874](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/dataframe/frame.py:7874)     return self.lazy().with_columns(*exprs, **named_exprs).collect(_eager=True)
> 
> File c:\Code\arbeit\mathtec\adlerlacke\.venv\Lib\site-packages\polars\lazyframe\frame.py:1708, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, no_optimization, streaming, background, _eager)
>    [1705](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/lazyframe/frame.py:1705) if background:
>    [1706](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/lazyframe/frame.py:1706)     return InProcessQuery(ldf.collect_concurrently())
> -> [1708](file:///C:/Code/arbeit/mathtec/adlerlacke/.venv/Lib/site-packages/polars/lazyframe/frame.py:1708) return wrap_df(ldf.collect())
> 
> ComputeError: the name: 'fallback' passed to `LazyFrame.with_columns` is duplicate
> 
> It's possible that multiple expressions are returning the same default column name. If this is the case, try renaming the columns with `.alias("new_name")` to avoid duplicate column names.
> 
> Error originated just after this operation:
> DF ["unique_id", "ds"]; PROJECT */2 COLUMNS; SELECTION: "None"

Looking into core.py I see that in the predict-method line 131 :
```python
                if fcsts_i.ndim == 1:
                    fcsts_i = fcsts_i[:, None]
                fcsts[i * h : (i + 1) * h, cuts[i_model] : cuts[i_model + 1]] = fcsts_i
            cols += cols_m
        return fcsts, cols #<---- HERE
```
the *cols* contain ["HistoricAverage","HistoricAverage","SeasonalNaive"], which in line 741
```python
        else:
            fcsts, cols = self._predict_parallel(h=h, X=X, level=level)
        fcsts_df = self._make_future_df(h=h)
        fcsts_df[cols] = fcsts # <------- HERE
        return fcsts_df
```

leads to the exception.
My guess: the edge case where multiple models fail and recurr to the fallback is not treated correctly.

### Versions / Dependencies

Pythonversion: 3.12.0

OS: Windows

Installed packages:

> absl-py==2.1.0
> adagio==0.2.4
> adbc-driver-manager==0.11.0
> adbc-driver-sqlite==0.11.0
> aiohttp==3.9.5
> aiosignal==1.3.1
> altair==5.1.2
> annotated-types==0.6.0
> appdirs==1.4.4
> asttokens==2.4.0
> attrs==23.1.0
> backcall==0.2.0
> bleach==6.1.0
> bokeh==3.4.1
> captum==0.7.0
> certifi==2024.2.2
> cffi==1.16.0
> charset-normalizer==3.3.2
> click==8.1.7
> cloudpickle==3.0.0
> colorama==0.4.6
> colorcet==3.1.0
> comm==0.1.4
> connectorx==0.2.3
> contourpy==1.2.1
> coreforecast==0.0.9
> cycler==0.12.1
> debugpy==1.8.0
> decorator==5.1.1
> deltalake==0.16.4
> executing==2.0.0
> fastjsonschema==2.18.1
> filelock==3.13.4
> fonttools==4.51.0
> frozenlist==1.4.1
> fs==2.4.16
> fsspec==2023.12.2
> fugue==0.9.0
> gevent==24.2.1
> greenlet==3.0.3
> grpcio==1.62.2
> holidays==0.47
> holoviews==1.18.3
> hvplot==0.9.2
> idna==3.7
> importlib_resources==6.4.0
> ipykernel==6.25.2
> ipython==8.16.1
> ipywidgets==8.1.2
> jedi==0.19.1
> Jinja2==3.1.2
> joblib==1.4.2
> jsonschema==4.19.1
> jsonschema-specifications==2023.7.1
> jupyter_client==8.3.1
> jupyter_core==5.4.0
> jupyterlab_widgets==3.0.10
> kaleido==0.1.0.post1
> kiwisolver==1.4.5
> lightning-utilities==0.11.2
> linkify-it-py==2.0.3
> livelossplot==0.5.5
> llvmlite==0.42.0
> Markdown==3.6
> markdown-it-py==3.0.0
> MarkupSafe==2.1.3
> matplotlib==3.8.4
> matplotlib-inline==0.1.6
> mdit-py-plugins==0.4.0
> mdurl==0.1.2
> mmhash3==3.0.1
> mpmath==1.3.0
> multidict==6.0.5
> nbformat==5.9.2
> nbstripout==0.6.1
> nest-asyncio==1.5.8
> networkx==3.3
> neuralprophet==0.8.0
> numba==0.59.1
> numpy==1.26.0
> packaging==23.2
> pandas==2.1.1
> panel==1.4.1
> param==2.1.0
> parso==0.8.3
> patsy==0.5.6
> pickleshare==0.7.5
> pillow==10.3.0
> platformdirs==3.11.0
> plotly==5.21.0
> polars==0.20.21
> prompt-toolkit==3.0.39
> protobuf==5.26.1
> psutil==5.9.5
> pure-eval==0.2.2
> pyarrow==15.0.2
> pyarrow-hotfix==0.6
> pycparser==2.22
> pydantic==2.7.0
> pydantic_core==2.18.1
> Pygments==2.16.1
> pyiceberg==0.6.0
> pyparsing==3.1.2
> python-dateutil==2.8.2
> pytorch-lightning==1.9.5
> pytz==2023.3.post1
> pyviz_comms==3.0.2
> pywin32==306
> PyYAML==6.0.1
> pyzmq==25.1.1
> referencing==0.30.2
> requests==2.31.0
> rich==13.7.1
> rpds-py==0.10.4
> rustworkx==0.14.2
> scikit-base==0.7.8
> scikit-learn==1.4.2
> scipy==1.13.0
> setuptools==69.5.1
> six==1.16.0
> sktime==0.29.0
> sortedcontainers==2.4.0
> SQLAlchemy==2.0.29
> stack-data==0.6.3
> statsforecast==1.7.4
> statsmodels==0.14.2
> strictyaml==1.7.3
> sympy==1.12
> tenacity==8.2.3
> tensorboard==2.16.2
> tensorboard-data-server==0.7.2
> threadpoolctl==3.5.0
> toolz==0.12.0
> torch==2.2.2
> torchmetrics==1.3.2
> tornado==6.3.3
> tqdm==4.66.2
> traitlets==5.11.2
> triad==0.9.6
> typing_extensions==4.11.0
> tzdata==2023.3
> uc-micro-py==1.0.3
> urllib3==2.2.1
> utilsforecast==0.1.10
> vegafusion==1.6.7
> vegafusion-python-embed==1.6.7
> vl-convert-python==1.3.0
> wcwidth==0.2.8
> webencodings==0.5.1
> Werkzeug==3.0.2
> widgetsnbextension==4.0.10
> xlsx2csv==0.8.2
> XlsxWriter==3.2.0
> xyzservices==2024.4.0
> yarl==1.9.4
> zope.event==5.0
> zope.interface==6.3

### Reproduction script

```python
# %%
import polars as pl
import io
from statsforecast import StatsForecast
from statsforecast.models import (
    AutoRegressive,
    HoltWinters,
    HistoricAverage,
    SeasonalNaive,
)

data = """
unique_id,ds,y,VMGWLag-2,VMGWLag-1,VMGWLag0,VMGWLag1,VMGWLag2
101004401504,2022-10-01T00:00:00.000000,0.0,0,0,0,0,0
101004401504,2022-11-01T00:00:00.000000,0.0,0,0,0,0,0
101004401504,2022-12-01T00:00:00.000000,0.0,7,0,0,0,0
101004401504,2023-01-01T00:00:00.000000,0.0,7,0,0,0,0
"""

df = pl.read_csv(io.StringIO(data), try_parse_dates=True)
train_data = df[:2]
test_data = df[2:]


strategies = [
    AutoRegressive(lags=[1, 2, 11, 12, 13], alias="ARLags1_2_11_12_13"),
    HoltWinters(season_length=12, alias="VERYDIFFERENT"),
    SeasonalNaive(season_length=12),
]

sf = StatsForecast(
    models=strategies,
    freq="1mo",
    n_jobs=-1,
    fallback_model=HistoricAverage(),
    verbose=True,
)

fit_result = sf.fit(df=train_data)
prediction = fit_result.predict(h=2, X_df=test_data.drop("y"))

# %%
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey @EddyXorb, thanks for using statsforecast and for the great example. I can reproduce the issue and I'll work on a fix.

**Comment by EddyXorb** [comment]
Thank you @jmoralez , I really appreciate your work, Nixtlaverse is fantastic.
