### ISSUE TITLE
Stability of the API

### ISSUE THREAD

**Issue by hrzn** [Nixtla/statsforecast#85]
Hi, great work on statsforecasts! This package looks very nice.
I'm considering integrating a couple of the models in Darts (https://github.com/unit8co/darts). I'm wondering about your future plans - do you intend to maintain this package on the long term? How likely can we expect API changes in the future releases?

Also as a side note - I took a quick look at the [Croston method](https://github.com/Nixtla/statsforecast/blob/main/statsforecast/models.py#L138),  and it looks like the method accepts `h` and `future_xreg`, which I'm not sure is intended as those are not used.

In general I think slightly more documentations on your different models could be helpful for users :)

**Comment by hrzn** [comment]
Perfect, thanks!
fyi: here's the PR into Darts to add AutoARIMA (called `AutoARIMASF` for the time being) and Croston. Is there anything else you'd recommend we should take a look at?

**Comment by hrzn** [comment]
> Hi @hrzn ! It would be great if the class name was StatsForecastAutoARIMA to match other libraries (sktime for example). Thanks! :)

Yes sure, I can do that 👍

**Comment by FedericoGarza** [comment]
Hi @hrzn. I've seen that StatsForecast is now included in darts. Thank you! Nice work! 
Let us know if you have any more questions or feature requests.

**Comment by hrzn** [comment]
Thanks for your work @FedericoGarza. Indeed it was released very recently and I'm very happy to see it in Darts. I'll let you know if I have any feedback (please do the same).
