### ISSUE TITLE
Add exogenous features support to statsforecast's cross-validation

### ISSUE THREAD

**Issue by quansun** [Nixtla/statsforecast#872]
### Description

It appears that while TimeGPT supports this functionality.

However, **statsforecast's cross-validation** does not currently allow for the inclusion of 'X_ts' (exogenous features in a dataframe). Is this an available feature, or is there a quick workaround to achieve this? Thanks!

**Comment by jmoralez** [comment]
Hey. Any extra columns (apart from id, time and target) are treated as exogenous features. The cross validation method doesn't require another argument because it already knows the future values.
