### ISSUE TITLE
MFLES clip number of arguments

### ISSUE THREAD

**Issue by atsangarides** [Nixtla/statsforecast#882]
### What happened + What you expected to happen

Trying to fit an AutoMFLES/FLES model and I get a 
```
TypeError: clip() takes at most 4 arguments (5 given)
```
when `cap_outliers` method is called in `fit()`

### Versions / Dependencies

statsforecast==1.7.6
pandas==2.2.2

### Reproduction script

```python
from statsforecast.models import MFLES

y = pd.Series(range(0, 12*7))
m = MFLES(
      season_length = [48],
)
m.fit(y=y)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by jmoralez** [comment]
Hey. If you use the model isolated like that you have to provide a numpy array, not a pandas series.

**Comment by atsangarides** [comment]
OMG, the type hinting is so clear...
